
package deathknight
// **************************************
// AUTO GENERATED BY SPELLS_PARSER.PY
// **************************************

import (
	"time"
    "github.com/WoWLegacySims/wotlk/sim/core"
)
var BloodBoilInfos = []*core.SpellInfo{
{SpellID:48721,MinLevel:58,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 88,Die: 19,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49939,MinLevel:66,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 115,Die: 25,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49940,MinLevel:72,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 148,Die: 33,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49941,MinLevel:78,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 179,Die: 41,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
}
var BloodStrikeInfos = []*core.SpellInfo{
{SpellID:45902,MinLevel:55,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 259,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 39,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 24,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49926,MinLevel:59,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 294,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 39,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 24,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49927,MinLevel:64,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 346,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 39,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 24,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49928,MinLevel:69,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 410,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 39,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 24,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49929,MinLevel:74,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 624,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 39,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 24,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49930,MinLevel:80,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 763,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 39,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 24,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
}
var DeathandDecayInfos = []*core.SpellInfo{
{SpellID:43265,MinLevel:60,MaxLevel:0,Duration:10000,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 25,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49936,MinLevel:67,MaxLevel:0,Duration:10000,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 33,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49937,MinLevel:73,MaxLevel:0,Duration:10000,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 48,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49938,MinLevel:80,MaxLevel:0,Duration:10000,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 61,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
}
var DeathCoilInfos = []*core.SpellInfo{
{SpellID:47541,MinLevel:55,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 166,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49892,MinLevel:62,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 207,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49893,MinLevel:68,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 274,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49894,MinLevel:76,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 380,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49895,MinLevel:80,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 442,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
}
var DeathStrikeInfos = []*core.SpellInfo{
{SpellID:49998,MinLevel:56,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 111,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 74,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 405,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49999,MinLevel:63,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 129,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 74,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 497,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:45463,MinLevel:70,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 164,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 74,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 629,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49923,MinLevel:75,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 249,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 74,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 1117,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49924,MinLevel:80,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 296,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 74,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 1309,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
}
var FrostStrikeInfos = []*core.SpellInfo{
{SpellID:49143,MinLevel:55,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 86,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 54,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:51416,MinLevel:60,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 102,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 54,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: -1,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:51417,MinLevel:65,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 114,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 54,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: -1,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:51418,MinLevel:70,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 141,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 54,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: -1,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:51419,MinLevel:75,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 200,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 54,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: -1,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:55268,MinLevel:80,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 249,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 54,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: -1,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
}
var HeartStrikeInfos = []*core.SpellInfo{
{SpellID:55050,MinLevel:55,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 249,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 49,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 9,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:55258,MinLevel:59,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 283,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 49,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 9,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:55259,MinLevel:64,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 333,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 49,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 9,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:55260,MinLevel:69,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 394,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 49,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 9,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:55261,MinLevel:74,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 600,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 49,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 9,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:55262,MinLevel:80,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 735,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 49,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 9,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
}
var HornofWinterInfos = []*core.SpellInfo{
{SpellID:57330,MinLevel:65,MaxLevel:0,Duration:120000,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 85,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 85,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 44,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:57623,MinLevel:75,MaxLevel:0,Duration:120000,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 154,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 154,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 44,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
}
var HowlingBlastInfos = []*core.SpellInfo{
{SpellID:49184,MinLevel:55,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 149,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 197,Die: 17,LevelScaling: 0,Coefficient: 0,},{BasePoints: 49,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:51409,MinLevel:70,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 149,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 323,Die: 29,LevelScaling: 0,Coefficient: 0,},{BasePoints: 49,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:51410,MinLevel:75,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 149,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 440,Die: 39,LevelScaling: 0,Coefficient: 0,},{BasePoints: 49,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:51411,MinLevel:80,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 149,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 517,Die: 45,LevelScaling: 0,Coefficient: 0,},{BasePoints: 49,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
}
var IcyTouchInfos = []*core.SpellInfo{
{SpellID:45477,MinLevel:55,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 126,Die: 11,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},{BasePoints: -1,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49896,MinLevel:61,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 143,Die: 13,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},{BasePoints: -1,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49903,MinLevel:67,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 160,Die: 13,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},{BasePoints: -1,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49904,MinLevel:73,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 186,Die: 17,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},{BasePoints: -1,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49909,MinLevel:78,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 226,Die: 19,LevelScaling: 0,Coefficient: 0,},{BasePoints: 109,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: -1,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
}
var ObliterateInfos = []*core.SpellInfo{
{SpellID:49020,MinLevel:61,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 247,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 79,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 24,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:51423,MinLevel:67,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 304,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 79,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 24,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:51424,MinLevel:73,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 476,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 79,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 24,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:51425,MinLevel:79,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 583,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 79,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 24,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
}
var PlagueStrikeInfos = []*core.SpellInfo{
{SpellID:45462,MinLevel:55,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 124,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 49,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49917,MinLevel:60,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 150,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 49,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49918,MinLevel:65,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 177,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 49,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49919,MinLevel:70,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 215,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 49,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49920,MinLevel:75,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 313,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 49,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:49921,MinLevel:80,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 377,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 49,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
}
var ScourgeStrikeInfos = []*core.SpellInfo{
{SpellID:55090,MinLevel:55,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 339,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 69,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 11,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:55265,MinLevel:67,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 417,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 69,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 11,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:55270,MinLevel:73,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 652,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 69,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 11,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:55271,MinLevel:79,MaxLevel:0,Duration:0,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]core.SpellEffect{{BasePoints: 799,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 69,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 11,Die: 1,LevelScaling: 0,Coefficient: 0,},},},
}
