
package core

// **************************************
// AUTO GENERATED BY MISC_PARSER.PY
// **************************************

import (
	"github.com/WoWLegacySims/wotlk/sim/core/stats"
)

var mixology = map[int32]float64{
28497: 1.444,
33721: 1.4,
53746: 1.444,
53748: 1.4,
53749: 1.4,
53751: 1.57,
53752: 1.8,
53755: 1.376,
53758: 1.5,
53760: 1.444,
53763: 1.35,
53764: 1.333,
54212: 1.444,
60340: 1.444,
60341: 1.444,
60343: 1.444,
60344: 1.444,
60345: 1.444,
60346: 1.444,
60347: 1.444,
62380: 1.8,
}
var Elixirs = map[int32]stats.Stats{
28104: {
stats.Strength: 15,stats.Agility: 15,stats.Stamina: 15,stats.Intellect: 15,stats.Spirit: 15,},
13453: {
stats.Strength: 18,stats.Stamina: 18,},
13454: {
stats.SpellPower: 35,stats.MeleeCrit: 10,stats.SpellCrit: 10,},
17708: {
stats.SpellPower: 15,},
21546: {
stats.SpellPower: 40,},
22824: {
stats.Strength: 35,},
22825: {
stats.Spirit: 24,stats.SpellPower: 24,},
22827: {
stats.SpellPower: 55,},
22831: {
stats.Agility: 30,stats.MeleeCrit: 12,stats.SpellCrit: 12,},
22833: {
stats.SpellPower: 55,},
22835: {
stats.SpellPower: 55,},
28102: {
stats.AttackPower: 60, stats.RangedAttackPower: 60,},
28103: {
stats.SpellPower: 24,stats.MeleeCrit: 24,stats.SpellCrit: 24,},
2457: {
stats.Agility: 4,},
31679: {
stats.AttackPower: 90, stats.RangedAttackPower: 90,stats.Stamina: -10,},
39666: {
stats.Agility: 45,},
40068: {
stats.AttackPower: 90, stats.RangedAttackPower: 90,},
40070: {
stats.SpellPower: 58,},
40073: {
stats.Strength: 50,},
40076: {
stats.Strength: 20,stats.Agility: 20,stats.Stamina: 20,stats.Intellect: 20,stats.Spirit: 20,},
44325: {
stats.MeleeHit: 45,stats.SpellHit: 45,},
44327: {
stats.MeleeCrit: 45,stats.SpellCrit: 45,},
44329: {
stats.Expertise: 45,},
44330: {
stats.ArmorPenetration: 45,},
44331: {
stats.MeleeHaste: 45,stats.SpellHaste: 45,},
45621: {
stats.MeleeHit: 10,stats.SpellHit: 10,},
13452: {
stats.Agility: 25,stats.MeleeCrit: 10,stats.SpellCrit: 10,},
6373: {
stats.SpellPower: 10,},
6662: {
stats.Strength: 8,},
8949: {
stats.Agility: 15,},
3391: {
stats.Strength: 8,},
3390: {
stats.Agility: 8,},
9155: {
stats.SpellPower: 20,},
9187: {
stats.Agility: 25,},
9206: {
stats.Strength: 25,},
9224: {
stats.AttackPower: 105, stats.RangedAttackPower: 105,},
9264: {
stats.SpellPower: 40,},
2454: {
stats.Strength: 4,},
40072: {
stats.Spirit: 50,},
13447: {
stats.Intellect: 18,stats.Spirit: 18,},
44332: {
stats.Intellect: 45,},
32063: {
},
32067: {
stats.Intellect: 30,stats.Spirit: 30,},
32068: {
stats.Resilience: 30,},
5997: {
stats.Armor: 50,},
3826: {
/*stats.HP5: 12,*/},
3825: {
stats.Health: 120,},
3389: {
stats.Armor: 150,},
2458: {
stats.Health: 27,},
3382: {
/*stats.HP5: 2,*/},
40078: {
stats.Health: 350,/*stats.HP5: 20,*/},
3383: {
stats.Intellect: 6,},
40097: {
stats.Armor: 800,},
44328: {
stats.Defense: 45,},
3388: {
/*stats.HP5: 6,*/},
40109: {
stats.MP5: 30,},
8951: {
stats.Armor: 250,},
13445: {
stats.Armor: 450,},
20004: {
/*stats.HP5: 20,*/},
20007: {
stats.MP5: 15,},
22192: {
stats.Dodge: 36,},
22193: {
stats.FireResistance: 15,stats.NatureResistance: 15,stats.FrostResistance: 15,stats.ShadowResistance: 15,stats.ArcaneResistance: 15,},
9179: {
stats.Intellect: 25,},
22834: {
stats.Armor: 550,},
9088: {
stats.ShadowResistance: 10,},
22848: {
stats.SpellPenetration: 30,},
32062: {
stats.Health: 250,/*stats.HP5: 10,*/},
22840: {
stats.MP5: 20,},
13513: {
stats.FireResistance: 25,stats.NatureResistance: 25,stats.FrostResistance: 25,stats.ShadowResistance: 25,stats.ArcaneResistance: 25,},
46379: {
stats.Health: 1300,},
46378: {
stats.MP5: 45,},
46377: {
stats.AttackPower: 180, stats.RangedAttackPower: 180,},
46376: {
stats.SpellPower: 125,},
13510: {
stats.Health: 400,},
44939: {
stats.FireResistance: 50,stats.NatureResistance: 50,stats.FrostResistance: 50,stats.ShadowResistance: 50,stats.ArcaneResistance: 50,},
13511: {
stats.Intellect: 65,},
13512: {
stats.SpellPower: 70,},
22851: {
stats.Health: 500,stats.Defense: 10,},
22866: {
stats.SpellPower: 80,},
22861: {
stats.SpellPower: 80,},
33208: {
stats.FireResistance: 35,stats.NatureResistance: 35,stats.FrostResistance: 35,stats.ShadowResistance: 35,stats.ArcaneResistance: 35,stats.Strength: 18,stats.Agility: 18,stats.Stamina: 18,stats.Intellect: 18,stats.Spirit: 18,},
22854: {
stats.AttackPower: 120, stats.RangedAttackPower: 120,},
22853: {
stats.MP5: 31,},
40079: {
stats.Resilience: 50,},
}