
package core

// **************************************
// AUTO GENERATED BY MISC_PARSER.PY
// **************************************

import (
	"github.com/WoWLegacySims/wotlk/sim/core/stats"
    "github.com/WoWLegacySims/wotlk/sim/core/proto"
)

var Mixology = map[int32]float64{
28497: 1.444,
33721: 1.4,
53746: 1.444,
53748: 1.4,
53749: 1.4,
53751: 1.57,
53752: 1.8,
53755: 1.376,
53758: 1.5,
53760: 1.444,
53763: 1.35,
53764: 1.333,
54212: 1.444,
60340: 1.444,
60341: 1.444,
60343: 1.444,
60344: 1.444,
60345: 1.444,
60346: 1.444,
60347: 1.444,
62380: 1.8,
}
var BattleElixirs = map[proto.BattleElixir]stats.Stats{
proto.BattleElixir_ElixirofMastery: {
stats.Strength: 15,stats.Agility: 15,stats.Stamina: 15,stats.Intellect: 15,stats.Spirit: 15,},
proto.BattleElixir_ElixirofBruteForce: {
stats.Strength: 18,stats.Stamina: 18,},
proto.BattleElixir_GreaterArcaneElixir: {
stats.SpellPower: 35,stats.MeleeCrit: 10,stats.SpellCrit: 10,},
proto.BattleElixir_ElixirofFrostPower: {
stats.SpellPower: 15,},
proto.BattleElixir_ElixirofGreaterFirepower: {
stats.SpellPower: 40,},
proto.BattleElixir_ElixirofMajorStrength: {
stats.Strength: 35,},
proto.BattleElixir_ElixirofHealingPower: {
stats.Spirit: 24,stats.SpellPower: 24,},
proto.BattleElixir_ElixirofMajorFrostPower: {
stats.SpellPower: 55,},
proto.BattleElixir_ElixirofMajorAgility: {
stats.Agility: 30,stats.MeleeCrit: 12,stats.SpellCrit: 12,},
proto.BattleElixir_ElixirofMajorFirepower: {
stats.SpellPower: 55,},
proto.BattleElixir_ElixirofMajorShadowPower: {
stats.SpellPower: 55,},
proto.BattleElixir_OnslaughtElixir: {
stats.AttackPower: 60, stats.RangedAttackPower: 60,},
proto.BattleElixir_AdeptsElixir: {
stats.SpellPower: 24,stats.MeleeCrit: 24,stats.SpellCrit: 24,},
proto.BattleElixir_ElixirofMinorAgility: {
stats.Agility: 4,},
proto.BattleElixir_FelStrengthElixir: {
stats.AttackPower: 90, stats.RangedAttackPower: 90,stats.Stamina: -10,},
proto.BattleElixir_ElixirofMightyAgility: {
stats.Agility: 45,},
proto.BattleElixir_WrathElixir: {
stats.AttackPower: 90, stats.RangedAttackPower: 90,},
proto.BattleElixir_SpellpowerElixir: {
stats.SpellPower: 58,},
proto.BattleElixir_ElixirofMightyStrength: {
stats.Strength: 50,},
proto.BattleElixir_GurusElixir: {
stats.Strength: 20,stats.Agility: 20,stats.Stamina: 20,stats.Intellect: 20,stats.Spirit: 20,},
proto.BattleElixir_ElixirofAccuracy: {
stats.MeleeHit: 45,stats.SpellHit: 45,},
proto.BattleElixir_ElixirofDeadlyStrikes: {
stats.MeleeCrit: 45,stats.SpellCrit: 45,},
proto.BattleElixir_ElixirofExpertise: {
stats.Expertise: 45,},
proto.BattleElixir_ElixirofArmorPiercing: {
stats.ArmorPenetration: 45,},
proto.BattleElixir_ElixirofLightningSpeed: {
stats.MeleeHaste: 45,stats.SpellHaste: 45,},
proto.BattleElixir_ElixirofMinorAccuracy: {
stats.MeleeHit: 10,stats.SpellHit: 10,},
proto.BattleElixir_ElixiroftheMongoose: {
stats.Agility: 25,stats.MeleeCrit: 10,stats.SpellCrit: 10,},
proto.BattleElixir_ElixirofFirepower: {
stats.SpellPower: 10,},
proto.BattleElixir_ElixirofGiantGrowth: {
stats.Strength: 8,},
proto.BattleElixir_ElixirofAgility: {
stats.Agility: 15,},
proto.BattleElixir_ElixirofOgresStrength: {
stats.Strength: 8,},
proto.BattleElixir_ElixirofLesserAgility: {
stats.Agility: 8,},
proto.BattleElixir_ArcaneElixir: {
stats.SpellPower: 20,},
proto.BattleElixir_ElixirofGreaterAgility: {
stats.Agility: 25,},
proto.BattleElixir_ElixirofGiants: {
stats.Strength: 25,},
proto.BattleElixir_ElixirofDemonslaying: {
stats.AttackPower: 105, stats.RangedAttackPower: 105,},
proto.BattleElixir_ElixirofShadowPower: {
stats.SpellPower: 40,},
proto.BattleElixir_ElixirofLionsStrength: {
stats.Strength: 4,},
}
var GuardianElixirs = map[proto.GuardianElixir]stats.Stats{
proto.GuardianElixir_ElixirofSpirit: {
stats.Spirit: 50,},
proto.GuardianElixir_ElixiroftheSages: {
stats.Intellect: 18,stats.Spirit: 18,},
proto.GuardianElixir_ElixirofMightyThoughts: {
stats.Intellect: 45,},
proto.GuardianElixir_EarthenElixir: {
},
proto.GuardianElixir_ElixirofDraenicWisdom: {
stats.Intellect: 30,stats.Spirit: 30,},
proto.GuardianElixir_ElixirofIronskin: {
stats.Resilience: 30,},
proto.GuardianElixir_ElixirofMinorDefense: {
stats.Armor: 50,},
proto.GuardianElixir_MajorTrollsBloodElixir: {
/*stats.HP5: 12,*/},
proto.GuardianElixir_ElixirofFortitude: {
stats.Health: 120,},
proto.GuardianElixir_ElixirofDefense: {
stats.Armor: 150,},
proto.GuardianElixir_ElixirofMinorFortitude: {
stats.Health: 27,},
proto.GuardianElixir_WeakTrollsBloodElixir: {
/*stats.HP5: 2,*/},
proto.GuardianElixir_ElixirofMightyFortitude: {
stats.Health: 350,/*stats.HP5: 20,*/},
proto.GuardianElixir_ElixirofWisdom: {
stats.Intellect: 6,},
proto.GuardianElixir_ElixirofProtection: {
stats.Armor: 800,},
proto.GuardianElixir_ElixirofMightyDefense: {
stats.Defense: 45,},
proto.GuardianElixir_StrongTrollsBloodElixir: {
/*stats.HP5: 6,*/},
proto.GuardianElixir_ElixirofMightyMageblood: {
stats.MP5: 30,},
proto.GuardianElixir_ElixirofGreaterDefense: {
stats.Armor: 250,},
proto.GuardianElixir_ElixirofSuperiorDefense: {
stats.Armor: 450,},
proto.GuardianElixir_MightyTrollsBloodElixir: {
/*stats.HP5: 20,*/},
proto.GuardianElixir_MagebloodElixir: {
stats.MP5: 15,},
proto.GuardianElixir_BloodkelpElixirofDodging: {
stats.Dodge: 36,},
proto.GuardianElixir_BloodkelpElixirofResistance: {
stats.FireResistance: 15,stats.NatureResistance: 15,stats.FrostResistance: 15,stats.ShadowResistance: 15,stats.ArcaneResistance: 15,},
proto.GuardianElixir_ElixirofGreaterIntellect: {
stats.Intellect: 25,},
proto.GuardianElixir_ElixirofMajorDefense: {
stats.Armor: 550,},
proto.GuardianElixir_GiftofArthas: {
stats.ShadowResistance: 10,},
proto.GuardianElixir_ElixirofEmpowerment: {
stats.SpellPenetration: 30,},
proto.GuardianElixir_ElixirofMajorFortitude: {
stats.Health: 250,/*stats.HP5: 10,*/},
proto.GuardianElixir_ElixirofMajorMageblood: {
stats.MP5: 20,},
}
var Flasks = map[proto.Flask]stats.Stats{
proto.Flask_FlaskofChromaticResistance: {
stats.FireResistance: 25,stats.NatureResistance: 25,stats.FrostResistance: 25,stats.ShadowResistance: 25,stats.ArcaneResistance: 25,},
proto.Flask_FlaskofStoneblood: {
stats.Health: 1300,},
proto.Flask_FlaskofPureMojo: {
stats.MP5: 45,},
proto.Flask_FlaskofEndlessRage: {
stats.AttackPower: 180, stats.RangedAttackPower: 180,},
proto.Flask_FlaskoftheFrostWyrm: {
stats.SpellPower: 125,},
proto.Flask_FlaskoftheTitans: {
stats.Health: 400,},
proto.Flask_LesserFlaskofResistance: {
stats.FireResistance: 50,stats.NatureResistance: 50,stats.FrostResistance: 50,stats.ShadowResistance: 50,stats.ArcaneResistance: 50,},
proto.Flask_FlaskofDistilledWisdom: {
stats.Intellect: 65,},
proto.Flask_FlaskofSupremePower: {
stats.SpellPower: 70,},
proto.Flask_FlaskofFortification: {
stats.Health: 500,stats.Defense: 10,},
proto.Flask_FlaskofPureDeath: {
stats.SpellPower: 80,},
proto.Flask_FlaskofBlindingLight: {
stats.SpellPower: 80,},
proto.Flask_FlaskofChromaticWonder: {
stats.FireResistance: 35,stats.NatureResistance: 35,stats.FrostResistance: 35,stats.ShadowResistance: 35,stats.ArcaneResistance: 35,stats.Strength: 18,stats.Agility: 18,stats.Stamina: 18,stats.Intellect: 18,stats.Spirit: 18,},
proto.Flask_FlaskofRelentlessAssault: {
stats.AttackPower: 120, stats.RangedAttackPower: 120,},
proto.Flask_FlaskofMightyRestoration: {
stats.MP5: 31,},
proto.Flask_LesserFlaskofToughness: {
stats.Resilience: 50,},
}
var Foods = map[proto.Food]stats.Stats{
proto.Food_GoretuskLiverPie: {
stats.Stamina: 4,stats.Spirit: 4,},
proto.Food_SeasonedWolfKabob: {
stats.Stamina: 6,stats.Spirit: 6,},
proto.Food_RedridgeGoulash: {
stats.Stamina: 6,stats.Spirit: 6,},
proto.Food_SpicedWolfMeat: {
stats.Stamina: 2,stats.Spirit: 2,},
proto.Food_CrabCake: {
stats.Stamina: 4,stats.Spirit: 4,},
proto.Food_CoyoteSteak: {
stats.Stamina: 4,stats.Spirit: 4,},
proto.Food_DryPorkRibs: {
stats.Stamina: 4,stats.Spirit: 4,},
proto.Food_BeerBastedBoarRibs: {
stats.Stamina: 2,stats.Spirit: 2,},
proto.Food_BloodSausage: {
stats.Stamina: 4,stats.Spirit: 4,},
proto.Food_CrocoliskSteak: {
stats.Stamina: 4,stats.Spirit: 4,},
proto.Food_MurlocFinSoup: {
stats.Stamina: 6,stats.Spirit: 6,},
proto.Food_CrocoliskGumbo: {
stats.Stamina: 6,stats.Spirit: 6,},
proto.Food_CuriouslyTastyOmelet: {
stats.Stamina: 6,stats.Spirit: 6,},
proto.Food_GooeySpiderCake: {
stats.Stamina: 6,stats.Spirit: 6,},
proto.Food_BigBearSteak: {
stats.Stamina: 6,stats.Spirit: 6,},
proto.Food_HotLionChops: {
stats.Stamina: 6,stats.Spirit: 6,},
proto.Food_TastyLionSteak: {
stats.Stamina: 8,stats.Spirit: 8,},
proto.Food_SoothingTurtleBisque: {
stats.Stamina: 8,stats.Spirit: 8,},
proto.Food_BarbecuedBuzzardWing: {
stats.Stamina: 8,stats.Spirit: 8,},
proto.Food_KaldoreiSpiderKabob: {
stats.Stamina: 2,stats.Spirit: 2,},
proto.Food_RoastedKodoMeat: {
stats.Stamina: 2,stats.Spirit: 2,},
proto.Food_FilletofFrenzy: {
stats.Stamina: 4,stats.Spirit: 4,},
proto.Food_StriderStew: {
stats.Stamina: 4,stats.Spirit: 4,},
proto.Food_CrispyLizardTail: {
stats.Stamina: 6,stats.Spirit: 6,},
proto.Food_LeanVenison: {
stats.Stamina: 6,stats.Spirit: 6,},
proto.Food_BoiledClams: {
stats.Stamina: 4,stats.Spirit: 4,},
proto.Food_GoblinDeviledClams: {
stats.Stamina: 6,stats.Spirit: 6,},
proto.Food_GiantClamScorcho: {
stats.Stamina: 8,stats.Spirit: 8,},
proto.Food_HerbBakedEgg: {
stats.Stamina: 2,stats.Spirit: 2,},
proto.Food_Lollipop: {
stats.Stamina: 2,stats.Spirit: 2,},
proto.Food_CandyBar: {
stats.Stamina: 2,stats.Spirit: 2,},
proto.Food_ChocolateSquare: {
stats.Stamina: 2,stats.Spirit: 2,},
proto.Food_CactusAppleSurprise: {
stats.Stamina: 2,stats.Spirit: 2,},
proto.Food_LeanWolfSteak: {
stats.Stamina: 6,stats.Spirit: 6,},
proto.Food_RoastRaptor: {
stats.Stamina: 8,stats.Spirit: 8,},
proto.Food_JungleStew: {
stats.Stamina: 8,stats.Spirit: 8,},
proto.Food_CarrionSurprise: {
stats.Stamina: 8,stats.Spirit: 8,},
proto.Food_MysteryStew: {
stats.Stamina: 8,stats.Spirit: 8,},
proto.Food_HeavyKodoStew: {
stats.Stamina: 12,stats.Spirit: 12,},
proto.Food_SpicedChiliCrab: {
stats.Stamina: 12,stats.Spirit: 12,},
proto.Food_MonsterOmelet: {
stats.Stamina: 12,stats.Spirit: 12,},
proto.Food_CrispyBatWing: {
stats.Stamina: 2,stats.Spirit: 2,},
proto.Food_HotWolfRibs: {
stats.Stamina: 8,stats.Spirit: 8,},
proto.Food_GrilledSquid: {
stats.Agility: 10,},
proto.Food_ClamletteSurprise: {
stats.Stamina: 12,stats.Spirit: 12,},
proto.Food_GingerbreadCookie: {
stats.Stamina: 2,stats.Spirit: 2,},
proto.Food_EggNog: {
stats.Stamina: 2,stats.Spirit: 2,},
proto.Food_SpiderSausage: {
stats.Stamina: 12,stats.Spirit: 12,},
proto.Food_TenderWolfSteak: {
stats.Stamina: 12,stats.Spirit: 12,},
proto.Food_HeavyCrocoliskStew: {
stats.Stamina: 8,stats.Spirit: 8,},
proto.Food_SmokedDesertDumplings: {
stats.Strength: 20,},
proto.Food_DirgesKickinChimaerokChops: {
stats.Stamina: 25,},
proto.Food_CrunchySpiderSurprise: {
stats.Stamina: 4,stats.Spirit: 4,},
proto.Food_CookiesJumboGumbo: {
stats.Stamina: 2,stats.Spirit: 2,},
proto.Food_RoastedMoongrazeTenderloin: {
stats.Stamina: 2,stats.Spirit: 2,},
proto.Food_MarshLichen: {
stats.Spirit: 10,},
proto.Food_EdibleFern: {
stats.Stamina: 14,stats.Spirit: 14,},
proto.Food_LynxSteak: {
stats.Stamina: 2,stats.Spirit: 2,},
proto.Food_BatBites: {
stats.Stamina: 4,stats.Spirit: 4,},
proto.Food_BuzzardBites: {
stats.Stamina: 20,stats.Spirit: 20,},
proto.Food_RavagerDog: {
stats.AttackPower: 40, stats.RangedAttackPower: 40,stats.Spirit: 20,},
proto.Food_BlackenedBasilisk: {
stats.SpellPower: 23,stats.Spirit: 20,},
proto.Food_RoastedClefthoof: {
stats.Strength: 20,stats.Spirit: 20,},
proto.Food_WarpBurger: {
stats.Agility: 20,stats.Spirit: 20,},
proto.Food_TalbukSteak: {
stats.Stamina: 20,stats.Spirit: 20,},
proto.Food_FeltailDelight: {
stats.Stamina: 20,stats.Spirit: 20,},
proto.Food_BlackenedSporefish: {
stats.Stamina: 20,stats.MP5: 10,},
proto.Food_GrilledMudfish: {
stats.Agility: 20,stats.Spirit: 20,},
proto.Food_PoachedBluefish: {
stats.SpellPower: 23,stats.Spirit: 20,},
proto.Food_GoldenFishSticks: {
stats.Spirit: 20,stats.SpellPower: 23,},
proto.Food_SpicyCrawdad: {
stats.Stamina: 30,stats.Spirit: 20,},
proto.Food_HelboarBacon: {
stats.Strength: 20,},
proto.Food_ClamBar: {
stats.Stamina: 20,stats.Spirit: 20,},
proto.Food_OronoksTuberofHealing: {
stats.Spirit: 20,stats.SpellPower: 23,},
proto.Food_OronoksTuberofAgility: {
stats.Agility: 20,stats.Spirit: 20,},
proto.Food_OronoksTuberofStrength: {
stats.Strength: 20,stats.Spirit: 20,},
proto.Food_OronoksTuberofSpellPower: {
stats.SpellPower: 23,stats.Spirit: 20,},
proto.Food_MokNathalShortribs: {
stats.Stamina: 20,stats.Spirit: 20,},
proto.Food_CrunchySerpent: {
stats.SpellPower: 23,stats.Spirit: 20,},
proto.Food_SkyguardRations: {
stats.Stamina: 15,stats.Spirit: 15,},
proto.Food_ClamletteMagnifique: {
stats.AttackPower: 24, stats.RangedAttackPower: 24,stats.SpellPower: 14,},
proto.Food_SavorySausage: {
stats.Stamina: 12,stats.Spirit: 12,},
proto.Food_PickledSausage: {
stats.Stamina: 14,stats.Spirit: 14,},
proto.Food_SpicySmokedSausage: {
stats.Stamina: 20,stats.Spirit: 20,},
proto.Food_TheGoldenLink: {
stats.Stamina: 20,stats.Spirit: 20,},
proto.Food_BarleybrewLight: {
stats.Stamina: 4,stats.Spirit: 4,},
proto.Food_BarleybrewDark: {
stats.Stamina: 6,stats.Spirit: 6,},
proto.Food_BarleybrewClear: {
stats.Stamina: 2,stats.Spirit: 2,},
proto.Food_Thunder45: {
stats.Stamina: 8,stats.Spirit: 8,},
proto.Food_ThunderbrewAle: {
stats.Stamina: 12,stats.Spirit: 12,},
proto.Food_ThunderbrewStout: {
stats.Stamina: 14,stats.Spirit: 14,},
proto.Food_GordokGrog: {
stats.Stamina: 20,stats.Spirit: 20,},
proto.Food_OgreMead: {
stats.Stamina: 20,stats.Spirit: 20,},
proto.Food_MuddersMilk: {
stats.Strength: 20,stats.Spirit: 20,},
proto.Food_TheEssentialBrewfestPretzel: {
stats.Stamina: 2,stats.Spirit: 2,},
proto.Food_FishermansFeast: {
stats.Stamina: 30,stats.Spirit: 20,},
proto.Food_SkullfishSoup: {
stats.MeleeCrit: 20,stats.SpellCrit: 20,stats.Spirit: 20,},
proto.Food_BroiledBloodfin: {
stats.FireResistance: 8,stats.NatureResistance: 8,stats.FrostResistance: 8,stats.ShadowResistance: 8,stats.ArcaneResistance: 8,},
proto.Food_SpicyHotTalbuk: {
stats.MeleeHit: 20,stats.SpellHit: 20,stats.Spirit: 20,},
proto.Food_SmallStepBrew: {
stats.Stamina: 2,stats.Spirit: 2,},
proto.Food_LongStrideBrew: {
stats.Stamina: 4,stats.Spirit: 4,},
proto.Food_PathofBrew: {
stats.Stamina: 6,stats.Spirit: 6,},
proto.Food_JungleRiverWater: {
stats.Stamina: 8,stats.Spirit: 8,},
proto.Food_BrewdooMagic: {
stats.Stamina: 12,stats.Spirit: 12,},
proto.Food_StoutShrunkenHead: {
stats.Stamina: 14,stats.Spirit: 14,},
proto.Food_DriedSausage: {
stats.Stamina: 6,stats.Spirit: 6,},
proto.Food_SucculentSausage: {
stats.Stamina: 8,stats.Spirit: 8,},
proto.Food_SpicedOnionCheese: {
stats.Stamina: 4,stats.Spirit: 4,},
proto.Food_ShoveltuskSoup: {
stats.MeleeHaste: 30,stats.SpellHaste: 30,stats.Stamina: 30,},
proto.Food_RecipeShoveltuskSoup: {
stats.MeleeHaste: 30,stats.SpellHaste: 30,stats.Stamina: 30,},
proto.Food_HoneyedHolidayHam: {
stats.Stamina: 20,stats.Spirit: 20,},
proto.Food_HotAppleCider: {
stats.Stamina: 20,stats.Spirit: 20,},
proto.Food_SparklingAppleCider: {
stats.Stamina: 12,stats.Spirit: 12,},
proto.Food_MammothMeal: {
stats.AttackPower: 60, stats.RangedAttackPower: 60,stats.Stamina: 30,},
proto.Food_ShoveltuskSteak: {
stats.SpellPower: 35,stats.Stamina: 30,},
proto.Food_WormDelight: {
stats.MeleeCrit: 30,stats.SpellCrit: 30,stats.Stamina: 30,},
proto.Food_RoastedWorg: {
stats.MeleeHaste: 30,stats.SpellHaste: 30,stats.Stamina: 30,},
proto.Food_RhinoDogs: {
stats.MP5: 15,stats.Stamina: 30,},
proto.Food_GreatFeast: {
stats.AttackPower: 60, stats.RangedAttackPower: 60,stats.Stamina: 30,stats.SpellPower: 35,},
proto.Food_MegaMammothMeal: {
stats.AttackPower: 80, stats.RangedAttackPower: 80,stats.Stamina: 40,},
proto.Food_TenderShoveltuskSteak: {
stats.SpellPower: 46,stats.Stamina: 40,},
proto.Food_SpicedWormBurger: {
stats.MeleeCrit: 40,stats.SpellCrit: 40,stats.Stamina: 40,},
proto.Food_VeryBurntWorg: {
stats.MeleeHaste: 40,stats.SpellHaste: 40,stats.Stamina: 40,},
proto.Food_MightyRhinoDogs: {
stats.MP5: 20,stats.Stamina: 40,},
proto.Food_GrilledSculpin: {
stats.AttackPower: 60, stats.RangedAttackPower: 60,stats.Stamina: 40,},
proto.Food_SmokedSalmon: {
stats.SpellPower: 35,stats.Stamina: 40,},
proto.Food_PoachedNettlefish: {
stats.MeleeCrit: 30,stats.SpellCrit: 30,stats.Stamina: 40,},
proto.Food_PickledFangtooth: {
stats.MP5: 15,stats.Stamina: 40,},
proto.Food_PoachedNorthernSculpin: {
stats.AttackPower: 80, stats.RangedAttackPower: 80,stats.Stamina: 40,},
proto.Food_FirecrackerSalmon: {
stats.SpellPower: 46,stats.Stamina: 40,},
proto.Food_SpicyBlueNettlefish: {
stats.MeleeCrit: 40,stats.SpellCrit: 40,stats.Stamina: 40,},
proto.Food_ImperialMantaSteak: {
stats.MeleeHaste: 40,stats.SpellHaste: 40,stats.Stamina: 40,},
proto.Food_CharredBearKabobs: {
stats.AttackPower: 24, stats.RangedAttackPower: 24,},
proto.Food_JuicyBearBurger: {
stats.SpellPower: 14,},
proto.Food_SucculentOrcaStew: {
stats.MeleeCrit: 30,stats.SpellCrit: 30,stats.Stamina: 30,},
proto.Food_RecipeSucculentOrcaStew: {
stats.Stamina: 6,stats.Spirit: 6,},
proto.Food_SteamingChickenSoup: {
stats.Stamina: 25,stats.Spirit: 25,},
proto.Food_BakedMantaRay: {
stats.MeleeHaste: 30,stats.SpellHaste: 30,stats.Stamina: 40,},
proto.Food_SpicyFriedHerring: {
stats.MP5: 20,stats.Stamina: 40,},
proto.Food_RhinoliciousWormsteak: {
stats.Expertise: 40,stats.Stamina: 40,},
proto.Food_HeartyRhino: {
stats.ArmorPenetration: 40,stats.Stamina: 40,},
proto.Food_SnapperExtreme: {
stats.MeleeHit: 40,stats.SpellHit: 40,stats.Stamina: 40,},
proto.Food_Cuttlesteak: {
stats.Spirit: 40,stats.Stamina: 40,},
proto.Food_BlackenedDragonfin: {
stats.Agility: 40,stats.Stamina: 40,},
proto.Food_DragonfinFilet: {
stats.Strength: 40,stats.Stamina: 40,},
proto.Food_FishFeast: {
stats.AttackPower: 80, stats.RangedAttackPower: 80,stats.Stamina: 40,stats.SpellPower: 46,},
proto.Food_DalaranClamChowder: {
stats.AttackPower: 60, stats.RangedAttackPower: 60,stats.Stamina: 30,stats.SpellPower: 35,},
proto.Food_SlipperyEel: {
stats.Dodge: 40,},
proto.Food_WorgTartare: {
stats.MeleeHit: 40,stats.SpellHit: 40,stats.Stamina: 40,},
proto.Food_ThundersPlunder: {
stats.Resilience: 40,stats.Stamina: 40,},
proto.Food_BarleybrewGold: {
stats.MeleeCrit: 40,stats.SpellCrit: 40,},
proto.Food_CrimsonStripe: {
stats.MeleeCrit: 40,stats.SpellCrit: 40,},
proto.Food_PromiseofthePandaren: {
stats.Resilience: 40,stats.Stamina: 40,},
proto.Food_ChuganpugsDelight: {
stats.MeleeCrit: 40,stats.SpellCrit: 40,},
proto.Food_BountifulBasket: {
stats.AttackPower: 8, stats.RangedAttackPower: 8,stats.Stamina: 4,stats.SpellPower: 4,},
}