
package core
// **************************************
// AUTO GENERATED BY SPELLS_PARSER.PY
// **************************************

import (
	"time"
)
var LifebloodInfos = []*SpellInfo{
{SpellID:55428,MinLevel:0,MaxLevel:0,Duration:5000,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]SpellEffect{{BasePoints: 59,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:55480,MinLevel:0,MaxLevel:0,Duration:5000,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]SpellEffect{{BasePoints: 95,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:55500,MinLevel:0,MaxLevel:0,Duration:5000,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]SpellEffect{{BasePoints: 143,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:55501,MinLevel:0,MaxLevel:0,Duration:5000,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]SpellEffect{{BasePoints: 179,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:55502,MinLevel:0,MaxLevel:0,Duration:5000,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]SpellEffect{{BasePoints: 239,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
{SpellID:55503,MinLevel:0,MaxLevel:0,Duration:5000,Period:0,CastTime: 0 * time.Millisecond,BaseCost: 0,Effects: [3]SpellEffect{{BasePoints: 719,Die: 1,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},{BasePoints: 0,Die: 0,LevelScaling: 0,Coefficient: 0,},},},
}
