import {Stat} from "../../proto/common";
import {BattleElixir,Flask,Food,GuardianElixir} from '../../proto/consumes_gen.js'
import { ActionId } from "../../proto_utils/action_id";
import { ConsumableStatOption } from "./consumables.js";

export const BATTLEELIXIR_CONFIG = [
{ config : {actionId: ActionId.fromItemId(28104), value: BattleElixir.ElixirofMastery}, stats: [Stat.StatStrength,Stat.StatAgility,Stat.StatStamina,Stat.StatIntellect,Stat.StatSpirit,],level: 50},
{ config : {actionId: ActionId.fromItemId(13453), value: BattleElixir.ElixirofBruteForce}, stats: [Stat.StatStrength,Stat.StatStamina,],level: 45},
{ config : {actionId: ActionId.fromItemId(13454), value: BattleElixir.GreaterArcaneElixir}, stats: [Stat.StatSpellPower,Stat.StatMeleeCrit,Stat.StatSpellCrit,],level: 47},
{ config : {actionId: ActionId.fromItemId(17708), value: BattleElixir.ElixirofFrostPower}, stats: [Stat.StatSpellPower,],level: 28},
{ config : {actionId: ActionId.fromItemId(21546), value: BattleElixir.ElixirofGreaterFirepower}, stats: [Stat.StatSpellPower,],level: 40},
{ config : {actionId: ActionId.fromItemId(22824), value: BattleElixir.ElixirofMajorStrength}, stats: [Stat.StatStrength,],level: 50},
{ config : {actionId: ActionId.fromItemId(22825), value: BattleElixir.ElixirofHealingPower}, stats: [Stat.StatSpirit,Stat.StatSpellPower,],level: 50},
{ config : {actionId: ActionId.fromItemId(22827), value: BattleElixir.ElixirofMajorFrostPower}, stats: [Stat.StatSpellPower,],level: 50},
{ config : {actionId: ActionId.fromItemId(22831), value: BattleElixir.ElixirofMajorAgility}, stats: [Stat.StatAgility,Stat.StatMeleeCrit,Stat.StatSpellCrit,],level: 55},
{ config : {actionId: ActionId.fromItemId(22833), value: BattleElixir.ElixirofMajorFirepower}, stats: [Stat.StatSpellPower,],level: 50},
{ config : {actionId: ActionId.fromItemId(22835), value: BattleElixir.ElixirofMajorShadowPower}, stats: [Stat.StatSpellPower,],level: 60},
{ config : {actionId: ActionId.fromItemId(28102), value: BattleElixir.OnslaughtElixir}, stats: [Stat.StatAttackPower,Stat.StatRangedAttackPower,],level: 50},
{ config : {actionId: ActionId.fromItemId(28103), value: BattleElixir.AdeptsElixir}, stats: [Stat.StatSpellPower,Stat.StatMeleeCrit,Stat.StatSpellCrit,],level: 50},
{ config : {actionId: ActionId.fromItemId(2457), value: BattleElixir.ElixirofMinorAgility}, stats: [Stat.StatAgility,],level: 2},
{ config : {actionId: ActionId.fromItemId(31679), value: BattleElixir.FelStrengthElixir}, stats: [Stat.StatAttackPower,Stat.StatRangedAttackPower,Stat.StatStamina,],level: 60},
{ config : {actionId: ActionId.fromItemId(39666), value: BattleElixir.ElixirofMightyAgility}, stats: [Stat.StatAgility,],level: 70},
{ config : {actionId: ActionId.fromItemId(40068), value: BattleElixir.WrathElixir}, stats: [Stat.StatAttackPower,Stat.StatRangedAttackPower,],level: 70},
{ config : {actionId: ActionId.fromItemId(40070), value: BattleElixir.SpellpowerElixir}, stats: [Stat.StatSpellPower,],level: 70},
{ config : {actionId: ActionId.fromItemId(40073), value: BattleElixir.ElixirofMightyStrength}, stats: [Stat.StatStrength,],level: 70},
{ config : {actionId: ActionId.fromItemId(40076), value: BattleElixir.GurusElixir}, stats: [Stat.StatStrength,Stat.StatAgility,Stat.StatStamina,Stat.StatIntellect,Stat.StatSpirit,],level: 70},
{ config : {actionId: ActionId.fromItemId(44325), value: BattleElixir.ElixirofAccuracy}, stats: [Stat.StatMeleeHit,Stat.StatSpellHit,],level: 70},
{ config : {actionId: ActionId.fromItemId(44327), value: BattleElixir.ElixirofDeadlyStrikes}, stats: [Stat.StatMeleeCrit,Stat.StatSpellCrit,],level: 70},
{ config : {actionId: ActionId.fromItemId(44329), value: BattleElixir.ElixirofExpertise}, stats: [Stat.StatExpertise,],level: 70},
{ config : {actionId: ActionId.fromItemId(44330), value: BattleElixir.ElixirofArmorPiercing}, stats: [Stat.StatArmorPenetration,],level: 70},
{ config : {actionId: ActionId.fromItemId(44331), value: BattleElixir.ElixirofLightningSpeed}, stats: [Stat.StatMeleeHaste,Stat.StatSpellHaste,],level: 70},
{ config : {actionId: ActionId.fromItemId(45621), value: BattleElixir.ElixirofMinorAccuracy}, stats: [Stat.StatMeleeHit,Stat.StatSpellHit,],level: 15},
{ config : {actionId: ActionId.fromItemId(13452), value: BattleElixir.ElixiroftheMongoose}, stats: [Stat.StatAgility,Stat.StatMeleeCrit,Stat.StatSpellCrit,],level: 46},
{ config : {actionId: ActionId.fromItemId(6373), value: BattleElixir.ElixirofFirepower}, stats: [Stat.StatSpellPower,],level: 18},
{ config : {actionId: ActionId.fromItemId(6662), value: BattleElixir.ElixirofGiantGrowth}, stats: [Stat.StatStrength,],level: 8},
{ config : {actionId: ActionId.fromItemId(8949), value: BattleElixir.ElixirofAgility}, stats: [Stat.StatAgility,],level: 27},
{ config : {actionId: ActionId.fromItemId(3391), value: BattleElixir.ElixirofOgresStrength}, stats: [Stat.StatStrength,],level: 20},
{ config : {actionId: ActionId.fromItemId(3390), value: BattleElixir.ElixirofLesserAgility}, stats: [Stat.StatAgility,],level: 18},
{ config : {actionId: ActionId.fromItemId(9155), value: BattleElixir.ArcaneElixir}, stats: [Stat.StatSpellPower,],level: 37},
{ config : {actionId: ActionId.fromItemId(9187), value: BattleElixir.ElixirofGreaterAgility}, stats: [Stat.StatAgility,],level: 38},
{ config : {actionId: ActionId.fromItemId(9206), value: BattleElixir.ElixirofGiants}, stats: [Stat.StatStrength,],level: 38},
{ config : {actionId: ActionId.fromItemId(9224), value: BattleElixir.ElixirofDemonslaying}, stats: [Stat.StatAttackPower,Stat.StatRangedAttackPower,],level: 40},
{ config : {actionId: ActionId.fromItemId(9264), value: BattleElixir.ElixirofShadowPower}, stats: [Stat.StatSpellPower,],level: 40},
{ config : {actionId: ActionId.fromItemId(2454), value: BattleElixir.ElixirofLionsStrength}, stats: [Stat.StatStrength,],level: 1},
] as ConsumableStatOption<BattleElixir>[];
export const GUARDIANELIXIR_CONFIG = [
{ config : {actionId: ActionId.fromItemId(40072), value: GuardianElixir.ElixirofSpirit}, stats: [Stat.StatSpirit,],level: 70},
{ config : {actionId: ActionId.fromItemId(13447), value: GuardianElixir.ElixiroftheSages}, stats: [Stat.StatIntellect,Stat.StatSpirit,],level: 44},
{ config : {actionId: ActionId.fromItemId(44332), value: GuardianElixir.ElixirofMightyThoughts}, stats: [Stat.StatIntellect,],level: 70},
{ config : {actionId: ActionId.fromItemId(32063), value: GuardianElixir.EarthenElixir}, stats: [],level: 50},
{ config : {actionId: ActionId.fromItemId(32067), value: GuardianElixir.ElixirofDraenicWisdom}, stats: [Stat.StatIntellect,Stat.StatSpirit,],level: 50},
{ config : {actionId: ActionId.fromItemId(32068), value: GuardianElixir.ElixirofIronskin}, stats: [Stat.StatResilience,],level: 55},
{ config : {actionId: ActionId.fromItemId(5997), value: GuardianElixir.ElixirofMinorDefense}, stats: [Stat.StatArmor,],level: 1},
{ config : {actionId: ActionId.fromItemId(3826), value: GuardianElixir.MajorTrollsBloodElixir}, stats: [],level: 26},
{ config : {actionId: ActionId.fromItemId(3825), value: GuardianElixir.ElixirofFortitude}, stats: [Stat.StatHealth,],level: 25},
{ config : {actionId: ActionId.fromItemId(3389), value: GuardianElixir.ElixirofDefense}, stats: [Stat.StatArmor,],level: 16},
{ config : {actionId: ActionId.fromItemId(2458), value: GuardianElixir.ElixirofMinorFortitude}, stats: [Stat.StatHealth,],level: 2},
{ config : {actionId: ActionId.fromItemId(3382), value: GuardianElixir.WeakTrollsBloodElixir}, stats: [],level: 1},
{ config : {actionId: ActionId.fromItemId(40078), value: GuardianElixir.ElixirofMightyFortitude}, stats: [Stat.StatHealth,],level: 70},
{ config : {actionId: ActionId.fromItemId(3383), value: GuardianElixir.ElixirofWisdom}, stats: [Stat.StatIntellect,],level: 10},
{ config : {actionId: ActionId.fromItemId(40097), value: GuardianElixir.ElixirofProtection}, stats: [Stat.StatArmor,],level: 70},
{ config : {actionId: ActionId.fromItemId(44328), value: GuardianElixir.ElixirofMightyDefense}, stats: [Stat.StatDefense,],level: 70},
{ config : {actionId: ActionId.fromItemId(3388), value: GuardianElixir.StrongTrollsBloodElixir}, stats: [],level: 15},
{ config : {actionId: ActionId.fromItemId(40109), value: GuardianElixir.ElixirofMightyMageblood}, stats: [Stat.StatMP5,],level: 70},
{ config : {actionId: ActionId.fromItemId(8951), value: GuardianElixir.ElixirofGreaterDefense}, stats: [Stat.StatArmor,],level: 29},
{ config : {actionId: ActionId.fromItemId(13445), value: GuardianElixir.ElixirofSuperiorDefense}, stats: [Stat.StatArmor,],level: 43},
{ config : {actionId: ActionId.fromItemId(20004), value: GuardianElixir.MightyTrollsBloodElixir}, stats: [],level: 53},
{ config : {actionId: ActionId.fromItemId(20007), value: GuardianElixir.MagebloodElixir}, stats: [Stat.StatMP5,],level: 40},
{ config : {actionId: ActionId.fromItemId(22192), value: GuardianElixir.BloodkelpElixirofDodging}, stats: [Stat.StatDodge,],level: 0},
{ config : {actionId: ActionId.fromItemId(22193), value: GuardianElixir.BloodkelpElixirofResistance}, stats: [Stat.StatFireResistance,Stat.StatNatureResistance,Stat.StatFrostResistance,Stat.StatShadowResistance,Stat.StatArcaneResistance,],level: 0},
{ config : {actionId: ActionId.fromItemId(9179), value: GuardianElixir.ElixirofGreaterIntellect}, stats: [Stat.StatIntellect,],level: 37},
{ config : {actionId: ActionId.fromItemId(22834), value: GuardianElixir.ElixirofMajorDefense}, stats: [Stat.StatArmor,],level: 55},
{ config : {actionId: ActionId.fromItemId(9088), value: GuardianElixir.GiftofArthas}, stats: [Stat.StatShadowResistance,],level: 38},
{ config : {actionId: ActionId.fromItemId(22848), value: GuardianElixir.ElixirofEmpowerment}, stats: [Stat.StatSpellPenetration,],level: 60},
{ config : {actionId: ActionId.fromItemId(32062), value: GuardianElixir.ElixirofMajorFortitude}, stats: [Stat.StatHealth,],level: 50},
{ config : {actionId: ActionId.fromItemId(22840), value: GuardianElixir.ElixirofMajorMageblood}, stats: [Stat.StatMP5,],level: 60},
] as ConsumableStatOption<GuardianElixir>[];
export const FLASK_CONFIG = [
{ config : {actionId: ActionId.fromItemId(13513), value: Flask.FlaskofChromaticResistance}, stats: [Stat.StatFireResistance,Stat.StatNatureResistance,Stat.StatFrostResistance,Stat.StatShadowResistance,Stat.StatArcaneResistance,],level: 50},
{ config : {actionId: ActionId.fromItemId(46379), value: Flask.FlaskofStoneblood}, stats: [Stat.StatHealth,],level: 75},
{ config : {actionId: ActionId.fromItemId(46378), value: Flask.FlaskofPureMojo}, stats: [Stat.StatMP5,],level: 75},
{ config : {actionId: ActionId.fromItemId(46377), value: Flask.FlaskofEndlessRage}, stats: [Stat.StatAttackPower,Stat.StatRangedAttackPower,],level: 75},
{ config : {actionId: ActionId.fromItemId(46376), value: Flask.FlaskoftheFrostWyrm}, stats: [Stat.StatSpellPower,],level: 75},
{ config : {actionId: ActionId.fromItemId(13510), value: Flask.FlaskoftheTitans}, stats: [Stat.StatHealth,],level: 50},
{ config : {actionId: ActionId.fromItemId(44939), value: Flask.LesserFlaskofResistance}, stats: [Stat.StatFireResistance,Stat.StatNatureResistance,Stat.StatFrostResistance,Stat.StatShadowResistance,Stat.StatArcaneResistance,],level: 70},
{ config : {actionId: ActionId.fromItemId(13511), value: Flask.FlaskofDistilledWisdom}, stats: [Stat.StatIntellect,],level: 50},
{ config : {actionId: ActionId.fromItemId(13512), value: Flask.FlaskofSupremePower}, stats: [Stat.StatSpellPower,],level: 50},
{ config : {actionId: ActionId.fromItemId(22851), value: Flask.FlaskofFortification}, stats: [Stat.StatHealth,Stat.StatDefense,],level: 65},
{ config : {actionId: ActionId.fromItemId(22866), value: Flask.FlaskofPureDeath}, stats: [Stat.StatSpellPower,],level: 65},
{ config : {actionId: ActionId.fromItemId(22861), value: Flask.FlaskofBlindingLight}, stats: [Stat.StatSpellPower,],level: 65},
{ config : {actionId: ActionId.fromItemId(33208), value: Flask.FlaskofChromaticWonder}, stats: [Stat.StatFireResistance,Stat.StatNatureResistance,Stat.StatFrostResistance,Stat.StatShadowResistance,Stat.StatArcaneResistance,Stat.StatStrength,Stat.StatAgility,Stat.StatStamina,Stat.StatIntellect,Stat.StatSpirit,],level: 65},
{ config : {actionId: ActionId.fromItemId(22854), value: Flask.FlaskofRelentlessAssault}, stats: [Stat.StatAttackPower,Stat.StatRangedAttackPower,],level: 65},
{ config : {actionId: ActionId.fromItemId(22853), value: Flask.FlaskofMightyRestoration}, stats: [Stat.StatMP5,],level: 65},
{ config : {actionId: ActionId.fromItemId(40079), value: Flask.LesserFlaskofToughness}, stats: [Stat.StatResilience,],level: 70},
] as ConsumableStatOption<Flask>[];
export const FOOD_CONFIG = [
{ config : {actionId: ActionId.fromItemId(724), value: Food.GoretuskLiverPie}, stats: [Stat.StatStamina,Stat.StatSpirit,],level: 5},
{ config : {actionId: ActionId.fromItemId(1082), value: Food.RedridgeGoulash}, stats: [Stat.StatStamina,Stat.StatSpirit,],level: 10},
{ config : {actionId: ActionId.fromItemId(3728), value: Food.TastyLionSteak}, stats: [Stat.StatStamina,Stat.StatSpirit,],level: 20},
{ config : {actionId: ActionId.fromItemId(12215), value: Food.HeavyKodoStew}, stats: [Stat.StatStamina,Stat.StatSpirit,],level: 35},
{ config : {actionId: ActionId.fromItemId(13928), value: Food.GrilledSquid}, stats: [Stat.StatAgility,],level: 35},
{ config : {actionId: ActionId.fromItemId(17198), value: Food.EggNog}, stats: [Stat.StatStamina,Stat.StatSpirit,],level: 1},
{ config : {actionId: ActionId.fromItemId(20452), value: Food.SmokedDesertDumplings}, stats: [Stat.StatStrength,],level: 45},
{ config : {actionId: ActionId.fromItemId(21023), value: Food.DirgesKickinChimaerokChops}, stats: [Stat.StatStamina,],level: 55},
{ config : {actionId: ActionId.fromItemId(24105), value: Food.RoastedMoongrazeTenderloin}, stats: [Stat.StatStamina,Stat.StatSpirit,],level: 0},
{ config : {actionId: ActionId.fromItemId(27651), value: Food.BuzzardBites}, stats: [Stat.StatStamina,Stat.StatSpirit,],level: 55},
{ config : {actionId: ActionId.fromItemId(27655), value: Food.RavagerDog}, stats: [Stat.StatAttackPower,Stat.StatRangedAttackPower,Stat.StatSpirit,],level: 55},
{ config : {actionId: ActionId.fromItemId(27657), value: Food.BlackenedBasilisk}, stats: [Stat.StatSpellPower,Stat.StatSpirit,],level: 55},
{ config : {actionId: ActionId.fromItemId(27658), value: Food.RoastedClefthoof}, stats: [Stat.StatStrength,Stat.StatSpirit,],level: 55},
{ config : {actionId: ActionId.fromItemId(27659), value: Food.WarpBurger}, stats: [Stat.StatAgility,Stat.StatSpirit,],level: 55},
{ config : {actionId: ActionId.fromItemId(27663), value: Food.BlackenedSporefish}, stats: [Stat.StatStamina,Stat.StatMP5,],level: 55},
{ config : {actionId: ActionId.fromItemId(27667), value: Food.SpicyCrawdad}, stats: [Stat.StatStamina,Stat.StatSpirit,],level: 55},
{ config : {actionId: ActionId.fromItemId(33004), value: Food.ClamletteMagnifique}, stats: [Stat.StatAttackPower,Stat.StatRangedAttackPower,Stat.StatSpellPower,],level: 35},
{ config : {actionId: ActionId.fromItemId(33024), value: Food.PickledSausage}, stats: [Stat.StatStamina,Stat.StatSpirit,],level: 45},
{ config : {actionId: ActionId.fromItemId(33825), value: Food.SkullfishSoup}, stats: [Stat.StatMeleeCrit,Stat.StatSpellCrit,Stat.StatSpirit,],level: 65},
{ config : {actionId: ActionId.fromItemId(33867), value: Food.BroiledBloodfin}, stats: [Stat.StatFireResistance,Stat.StatNatureResistance,Stat.StatFrostResistance,Stat.StatShadowResistance,Stat.StatArcaneResistance,],level: 55},
{ config : {actionId: ActionId.fromItemId(33872), value: Food.SpicyHotTalbuk}, stats: [Stat.StatMeleeHit,Stat.StatSpellHit,Stat.StatSpirit,],level: 65},
{ config : {actionId: ActionId.fromItemId(34754), value: Food.MegaMammothMeal}, stats: [Stat.StatAttackPower,Stat.StatRangedAttackPower,Stat.StatStamina,],level: 70},
{ config : {actionId: ActionId.fromItemId(34755), value: Food.TenderShoveltuskSteak}, stats: [Stat.StatSpellPower,Stat.StatStamina,],level: 70},
{ config : {actionId: ActionId.fromItemId(34756), value: Food.SpicedWormBurger}, stats: [Stat.StatMeleeCrit,Stat.StatSpellCrit,Stat.StatStamina,],level: 70},
{ config : {actionId: ActionId.fromItemId(34758), value: Food.MightyRhinoDogs}, stats: [Stat.StatMP5,Stat.StatStamina,],level: 70},
{ config : {actionId: ActionId.fromItemId(34769), value: Food.ImperialMantaSteak}, stats: [Stat.StatMeleeHaste,Stat.StatSpellHaste,Stat.StatStamina,],level: 70},
{ config : {actionId: ActionId.fromItemId(35563), value: Food.CharredBearKabobs}, stats: [Stat.StatAttackPower,Stat.StatRangedAttackPower,],level: 45},
{ config : {actionId: ActionId.fromItemId(35565), value: Food.JuicyBearBurger}, stats: [Stat.StatSpellPower,],level: 45},
{ config : {actionId: ActionId.fromItemId(42994), value: Food.RhinoliciousWormsteak}, stats: [Stat.StatExpertise,Stat.StatStamina,],level: 70},
{ config : {actionId: ActionId.fromItemId(42995), value: Food.HeartyRhino}, stats: [Stat.StatArmorPenetration,Stat.StatStamina,],level: 70},
{ config : {actionId: ActionId.fromItemId(42996), value: Food.SnapperExtreme}, stats: [Stat.StatMeleeHit,Stat.StatSpellHit,Stat.StatStamina,],level: 70},
{ config : {actionId: ActionId.fromItemId(42998), value: Food.Cuttlesteak}, stats: [Stat.StatSpirit,Stat.StatStamina,],level: 70},
{ config : {actionId: ActionId.fromItemId(42999), value: Food.BlackenedDragonfin}, stats: [Stat.StatAgility,Stat.StatStamina,],level: 70},
{ config : {actionId: ActionId.fromItemId(43000), value: Food.DragonfinFilet}, stats: [Stat.StatStrength,Stat.StatStamina,],level: 70},
{ config : {actionId: ActionId.fromItemId(43015), value: Food.FishFeast}, stats: [Stat.StatAttackPower,Stat.StatRangedAttackPower,Stat.StatStamina,Stat.StatSpellPower,],level: 70},
{ config : {actionId: ActionId.fromItemId(46399), value: Food.ThundersPlunder}, stats: [Stat.StatResilience,Stat.StatStamina,],level: 75},
] as ConsumableStatOption<Food>[];
