#!/usr/bin/python

import csv
import mysql.connector
from typing import List

# Generates go/ts baes stats files from assets/db_inputs/basestats

BASE_DIR = ""

DIR_PATH = "assets/db_inputs/basestats/"
GO_OUTPUT_PATH = "sim/core/base_stats_auto_gen.go"
TS_OUTPUT_PATH = "ui/core/constants/ratings.ts"

MELEE_CRIT = "chancetomeleecrit.txt"
MELEE_CRIT_BASE = "chancetomeleecritbase.txt"
SPELL_CRIT = "chancetospellcrit.txt"
SPELL_CRIT_BASE = "chancetospellcritbase.txt"
COMBAT_RATINGS = "combatratings.txt"
MP_PER_SPIRIT = "GtRegenMPPerSpt.csv"

BASE_LEVEL = 80

Offs = {
    "Warrior": 0,
    "Paladin": 1,
    "Hunter": 2,
    "Rogue": 3,
    "Priest": 4,
    "Death Knight": 5,
    "Shaman": 6,
    "Mage": 7,
    "Warlock": 8,
    "Monk": 9,
    "Druid": 10,
}

#Warrior	Paladin	Hunter	Rogue	Priest	Death Knight	Shaman	Mage	Warlock	Monk	Druid
def GenIndexedDb(file : str):
    db = {}
    with open(file) as tsv:
        first = True
        for line in csv.reader(tsv, delimiter="\t"):
            if first:
                first = False
                continue
            db[line[0]] = line[1:]
    return db

def GenRowIndexedDb(file : str):
    db = {}
    with open(file) as tsv:
        first = True
        for col in zip(*[line for line in csv.reader(tsv, delimiter='\t')]):
            if first:
                first = False
                continue
            db[col[0]] = list(col[1:])
    return db

class ClassStats:
    MCrit : dict
    SCrit : dict
    MCritBase : dict
    SCritBase : dict
    CombatRatings : dict
    MpPerSpirit : dict

class ClassLevelStats:
    Class: int
    Level: int
    BaseHP: int
    BaseMana: int
    Strength: int
    Agility: int
    Stamina: int
    Intellect: int
    Spirit: int

def GetClass(Class: int):
    return ["Warrior","Paladin","Hunter","Rogue","Priest","Deathknight","Shaman","Mage","Warlock","","Druid"][Class-1]

def GenExtraStatsGoFile(cs: ClassStats, ls: List[ClassLevelStats]):
    header = '''
package core

// **************************************
// AUTO GENERATED BY BASE_STATS_PARSER.PY
// **************************************

import (
	"github.com/WoWLegacySims/wotlk/sim/core/proto"
	"github.com/WoWLegacySims/wotlk/sim/core/stats"
)

'''
    output = header
    output += f"const ExpertisePerQuarterPercentReduction = {cs.CombatRatings['expertise'][BASE_LEVEL-1]}\n"
    output += f"const HasteRatingPerHastePercent = {cs.CombatRatings['haste melee'][BASE_LEVEL-1]}\n"
    output += f"const CritRatingPerCritChance = {cs.CombatRatings['crit melee'][BASE_LEVEL-1]}\n"
    output += f"const MeleeHitRatingPerHitChance = {cs.CombatRatings['hit melee'][BASE_LEVEL-1]}\n"
    output += f"const SpellHitRatingPerHitChance = {cs.CombatRatings['hit spell'][BASE_LEVEL-1]}\n"
    output += f"const DefenseRatingPerDefense = {cs.CombatRatings['defense skill'][BASE_LEVEL-1]}\n"
    output += f"const DodgeRatingPerDodgeChance = {cs.CombatRatings['dodge'][BASE_LEVEL-1]}\n"
    output += f"const ParryRatingPerParryChance = {cs.CombatRatings['parry'][BASE_LEVEL-1]}\n"
    output += f"const BlockRatingPerBlockChance = {cs.CombatRatings['block'][BASE_LEVEL-1]}\n"
    output += f"const ResilienceRatingPerCritReductionChance = {cs.CombatRatings['crit taken melee'][BASE_LEVEL-1]}\n"
    output += f"const ArmorPenPerPercentArmor = {float(cs.CombatRatings['armor pen'][BASE_LEVEL-1])/1.1}\n"
    output += f"const MPPerSpirit = {float(cs.MpPerSpirit['Paladin'][BASE_LEVEL-1])}\n"
    output += f"const CritPerInt = {float(cs.SCrit[str(BASE_LEVEL)][2])*100}\n"

    output += '''var CritPerAgiMaxLevel = map[proto.Class]float64{
proto.Class_ClassUnknown: 0.0,'''
    for c in ["Warrior", "Paladin", "Hunter", "Rogue", "Priest", "Death Knight", "Shaman", "Mage", "Warlock", "Druid"]:
        cName = c.split()
        if len(cName) > 1:
            cName[1] = cName[1].lower()
        cName = ''.join(cName)
        mc = float(cs.MCrit[str(BASE_LEVEL)][Offs[c]])*100
        output += f"\nproto.Class_Class{cName}: {mc:.6},"
    output += "\n}\n"

    output += '''var BaseCrit = map[proto.Class]stats.Stats{
proto.Class_ClassUnknown: {},'''
    for c in ["Warrior", "Paladin", "Hunter", "Rogue", "Priest", "Death Knight", "Shaman", "Mage", "Warlock", "Druid"]:
        cName = c.split()
        if len(cName) > 1:
            cName[1] = cName[1].lower()
        cName = ''.join(cName)
        output += f"\nproto.Class_Class{cName}: {{"
        scb = float(cs.SCritBase["1"][Offs[c]])*100
        mcb = float(cs.MCritBase["1"][Offs[c]])*100
        output += f"\n stats.SpellCrit: {scb:.6}*CritRatingPerCritChance,"
        output += f"\n stats.MeleeCrit: {mcb:.6}*CritRatingPerCritChance,"
        output += "\n},"
    output += "\n}\n"

    output += '''var ClassBaseStats = map[proto.Class]stats.Stats{\nproto.Class_ClassUnknown: {'''
    currentClass = 0
    for l in ls:
        if (currentClass != l.Class):
            currentClass = l.Class
            output += f"}},\nproto.Class_Class{GetClass(l.Class)}: {{\n"

        output += f"stats.Health: {l.BaseHP}, stats.Mana: {l.BaseMana}, stats.Strength: {l.Strength}, stats.Agility: {l.Agility}, stats.Stamina: {l.Stamina}, stats.Intellect: {l.Intellect}, stats.Spirit: {l.Spirit},\n"
    output += "\n},\n}\n"

    return output

def GenExtraStatsTSFile(cs: ClassStats):
    header = '''
// **************************************
// AUTO GENERATED BY BASE_STATS_PARSER.PY
// **************************************

'''

    output = header
    output += f"export const EXPERTISE_PER_QUARTER_PERCENT_REDUCTION = {cs.CombatRatings['expertise'][BASE_LEVEL-1]}\n"
    output += f"export const HASTE_RATING_PER_HASTE_PERCENT = {cs.CombatRatings['haste melee'][BASE_LEVEL-1]}\n"
    output += f"export const CRIT_RATING_PER_CRIT_CHANCE = {cs.CombatRatings['crit melee'][BASE_LEVEL-1]}\n"
    output += f"export const MELEE_HIT_RATING_PER_HIT_CHANCE = {cs.CombatRatings['hit melee'][BASE_LEVEL-1]}\n"
    output += f"export const SPELL_HIT_RATING_PER_HIT_CHANCE = {cs.CombatRatings['hit spell'][BASE_LEVEL-1]}\n"
    output += f"export const DEFENSE_RATING_PER_DEFENSE = {cs.CombatRatings['defense skill'][BASE_LEVEL-1]}\n"
    output += f"export const DODGE_RATING_PER_DODGE_CHANCE = {cs.CombatRatings['dodge'][BASE_LEVEL-1]}\n"
    output += f"export const PARRY_RATING_PER_PARRY_CHANCE = {cs.CombatRatings['parry'][BASE_LEVEL-1]}\n"
    output += f"export const BLOCK_RATING_PER_BLOCK_CHANCE = {cs.CombatRatings['block'][BASE_LEVEL-1]}\n"
    output += f"export const RESILIENCE_RATING_PER_CRIT_REDUCTION_CHANCE = {cs.CombatRatings['crit taken melee'][BASE_LEVEL-1]}\n"
    output += f"export const ARMOR_PEN_PER_PERCENT_ARMOR = {float(cs.CombatRatings['armor pen'][BASE_LEVEL-1])/1.1}\n"
    output += f"export const MP_PER_SPIRIT = {float(cs.MpPerSpirit['Paladin'][BASE_LEVEL-1])}\n"
    output += f"export const CRIT_PER_INT = {float(cs.SCrit[str(BASE_LEVEL)][2])*100}\n"
    return output



if __name__ == "__main__":
    db = mysql.connector.connect(host="localhost", user="root", password="root", database="acore_world")

    cursor = db.cursor()
    cursor.execute("SELECT * FROM player_class_stats WHERE Level = 80")
    results = cursor.fetchall()
    stats = []
    for x in results:
        level = ClassLevelStats()
        level.Class = x[0]
        level.Level = x[1]
        level.BaseHP = x[2]
        level.BaseMana = x[3]
        level.Strength = x[4]
        level.Agility = x[5]
        level.Stamina = x[6]
        level.Intellect = x[7]
        level.Spirit = x[7]
        stats.append(level)

    args = ClassStats()
    args.MCrit = GenIndexedDb(BASE_DIR + DIR_PATH + MELEE_CRIT)
    args.SCrit = GenIndexedDb(BASE_DIR + DIR_PATH + SPELL_CRIT)
    args.MCritBase = GenIndexedDb(BASE_DIR + DIR_PATH + MELEE_CRIT_BASE)
    args.SCritBase = GenIndexedDb(BASE_DIR + DIR_PATH + SPELL_CRIT_BASE)
    args.CombatRatings = GenRowIndexedDb(BASE_DIR + DIR_PATH + COMBAT_RATINGS)
    args.MpPerSpirit = GenRowIndexedDb(BASE_DIR + DIR_PATH + MP_PER_SPIRIT)

    output = GenExtraStatsGoFile(args, stats)
    fname = BASE_DIR + GO_OUTPUT_PATH
    print(f"Writing stats to: {fname}")
    f = open(fname, "w")
    f.write(output)
    f.close()

    output = GenExtraStatsTSFile(args)
    fname = BASE_DIR + TS_OUTPUT_PATH
    print(f"Writing stats to: {fname}")
    f = open(fname, "w")
    f.write(output)
    f.close()
