#!/usr/bin/python

import csv

# Generates go/ts baes stats files from assets/db_inputs/basestats

BASE_DIR = ""

DIR_PATH = "assets/db_inputs/basestats/"
OUTPUT_PATH = "sim/core/"

MELEE_CRIT = "chancetomeleecrit.txt"
MELEE_CRIT_BASE = "chancetomeleecritbase.txt"
SPELL_CRIT = "chancetospellcrit.txt"
SPELL_CRIT_BASE = "chancetospellcritbase.txt"
COMBAT_RATINGS = "combatratings.txt"
RATING_SCALAR = "octclasscombatratingscalar.txt"

BASE_LEVEL = 80

Offs = {
    "Warrior": 0,
    "Paladin": 1,
    "Hunter": 2,
    "Rogue": 3,
    "Priest": 4,
    "Death Knight": 5,
    "Shaman": 6,
    "Mage": 7,
    "Warlock": 8,
    "Monk": 9,
    "Druid": 10,
}

#Warrior	Paladin	Hunter	Rogue	Priest	Death Knight	Shaman	Mage	Warlock	Monk	Druid
def GenIndexedDb(file : str):
    db = {}
    with open(file) as tsv:
        first = True
        for line in csv.reader(tsv, delimiter="\t"):
            if first:
                first = False
                continue
            db[line[0]] = line[1:]
    return db

def GenRowIndexedDb(file : str):
    db = {}
    with open(file) as tsv:
        first = True
        for col in zip(*[line for line in csv.reader(tsv, delimiter='\t')]):
            if first:
                first = False
                continue
            db[col[0]] = list(col[1:])
    return db

class ClassStats:
    MCrit : dict
    SCrit : dict
    MCritBase : dict
    SCritBase : dict
    CombatRatings : dict

def GenRatingPerLevel(rating: dict, variable: str, key: str):
    output = f"var {variable} = map[int32]float64{{"
    for i in range(1,81):
        output += f"{i}:{rating[key][i-1]},"
    output += '''}\n'''
    return output

def GenExtraStatsGoFile(cs: ClassStats):
    header = '''
package core

// **************************************
// AUTO GENERATED BY BASE_STATS_PARSER.PY
// **************************************

import (
	"github.com/WoWLegacySims/wotlk/sim/core/proto"
	"github.com/WoWLegacySims/wotlk/sim/core/stats"
)

'''
    output = header
    output += GenRatingPerLevel(cs.CombatRatings,"ExpertisePerQuarterPercentReduction","weapon skill")
    output += GenRatingPerLevel(cs.CombatRatings,"HasteRatingPerHastePercent","haste melee")
    output += GenRatingPerLevel(cs.CombatRatings,"CritRatingPerCritChance","crit melee")
    output += GenRatingPerLevel(cs.CombatRatings,"MeleeHitRatingPerHitChance","hit melee")
    output += GenRatingPerLevel(cs.CombatRatings,"SpellHitRatingPerHitChance","hit spell")
    output += GenRatingPerLevel(cs.CombatRatings,"DefenseRatingPerDefense","defense skill")
    output += GenRatingPerLevel(cs.CombatRatings,"DodgeRatingPerDodgeChance","dodge")
    output += GenRatingPerLevel(cs.CombatRatings,"ParryRatingPerParryChance","parry")
    output += GenRatingPerLevel(cs.CombatRatings,"BlockRatingPerBlockChance","block")
    output += GenRatingPerLevel(cs.CombatRatings,"ResilienceRatingPerCritReductionChance","crit taken melee")

    output += '''\nvar CritPer = map[proto.Class]map[int32]float64{
proto.Class_ClassUnknown:{'''
    for i in range(1,81):
        output += f"{i}:0.0,"
    output += '''},'''

    for c in ["Warrior", "Paladin", "Hunter", "Rogue", "Priest", "Death Knight", "Shaman", "Mage", "Warlock", "Druid"]:
        cName = c.split()
        if len(cName) > 1:
            cName[1] = cName[1].lower()
        cName = ''.join(cName)
        output += f"\nproto.Class_Class{cName}: {{"
        for i in range(1,81):
            mc = float(cs.MCrit[str(i)][Offs[c]])*100
            output += f"{i}:{mc:.4f},"
        output += '''},'''
    output += "\n}\n"

    output += '''var BaseCrit = map[proto.Class]stats.Stats{
proto.Class_ClassUnknown: {},'''
    for c in ["Warrior", "Paladin", "Hunter", "Rogue", "Priest", "Death Knight", "Shaman", "Mage", "Warlock", "Druid"]:
        cName = c.split()
        if len(cName) > 1:
            cName[1] = cName[1].lower()
        cName = ''.join(cName)
        output += f"\nproto.Class_Class{cName}: {{"
        scb = float(cs.SCritBase["1"][Offs[c]])*100
        mcb = float(cs.MCritBase["1"][Offs[c]])*100
        output += f"\n stats.SpellCrit: {scb:.4f},"
        output += f"\n stats.MeleeCrit: {mcb:.4f},"
        output += "\n},"
    output += "\n}\n"
    return output


if __name__ == "__main__":
    args = ClassStats()
    args.MCrit = GenIndexedDb(BASE_DIR + DIR_PATH + MELEE_CRIT)
    args.SCrit = GenIndexedDb(BASE_DIR + DIR_PATH + SPELL_CRIT)
    args.MCritBase = GenIndexedDb(BASE_DIR + DIR_PATH + MELEE_CRIT_BASE)
    args.SCritBase = GenIndexedDb(BASE_DIR + DIR_PATH + SPELL_CRIT_BASE)
    args.CombatRatings = GenRowIndexedDb(BASE_DIR + DIR_PATH + COMBAT_RATINGS)

    output = GenExtraStatsGoFile(args)
    fname = BASE_DIR + OUTPUT_PATH + "base_stats_auto_gen.go"
    print(f"Writing stats to: {fname}")
    f = open(fname, "w")
    f.write(output)
    f.close()
