#!/usr/bin/python

import csv
import mysql.connector
from typing import List

# Generates go/ts baes stats files from assets/db_inputs/basestats

BASE_DIR = ""

DIR_PATH = "assets/db_inputs/basestats/"
GO_OUTPUT_PATH = "sim/core/base_stats_auto_gen.go"
TS_OUTPUT_PATH = "ui/core/constants/ratings.ts"

MELEE_CRIT = "chancetomeleecrit.txt"
MELEE_CRIT_BASE = "chancetomeleecritbase.txt"
SPELL_CRIT = "chancetospellcrit.txt"
SPELL_CRIT_BASE = "chancetospellcritbase.txt"
COMBAT_RATINGS = "combatratings.txt"
RATING_SCALAR = "octclasscombatratingscalar.txt"

BASE_LEVEL = 80

Offs = {
    "Warrior": 0,
    "Paladin": 1,
    "Hunter": 2,
    "Rogue": 3,
    "Priest": 4,
    "Death Knight": 5,
    "Shaman": 6,
    "Mage": 7,
    "Warlock": 8,
    "Monk": 9,
    "Druid": 10,
}

#Warrior	Paladin	Hunter	Rogue	Priest	Death Knight	Shaman	Mage	Warlock	Monk	Druid
def GenIndexedDb(file : str):
    db = {}
    with open(file) as tsv:
        first = True
        for line in csv.reader(tsv, delimiter="\t"):
            if first:
                first = False
                continue
            db[line[0]] = line[1:]
    return db

def GenRowIndexedDb(file : str):
    db = {}
    with open(file) as tsv:
        first = True
        for col in zip(*[line for line in csv.reader(tsv, delimiter='\t')]):
            if first:
                first = False
                continue
            db[col[0]] = list(col[1:])
    return db

class ClassStats:
    MCrit : dict
    SCrit : dict
    MCritBase : dict
    SCritBase : dict
    CombatRatings : dict

class ClassLevelStats:
    Class: int
    Level: int
    BaseHP: int
    BaseMana: int
    Strength: int
    Agility: int
    Stamina: int
    Intellect: int
    Spirit: int

def GetClass(Class: int):
    return ["Warrior","Paladin","Hunter","Rogue","Priest","Deathknight","Shaman","Mage","Warlock","","Druid"][Class-1]

def GenGORatingPerLevel(rating: dict, variable: str, key: str):
    output = f"var {variable} = map[int32]float64{{"
    for i in range(1,81):
        output += f"{i}:{rating[key][i-1]},"
    output += '''}\n'''
    return output

def GenExtraStatsGoFile(cs: ClassStats, ls: List[ClassLevelStats]):
    header = '''
package core

// **************************************
// AUTO GENERATED BY BASE_STATS_PARSER.PY
// **************************************

import (
	"github.com/WoWLegacySims/wotlk/sim/core/proto"
	"github.com/WoWLegacySims/wotlk/sim/core/stats"
)

'''
    output = header
    output += GenGORatingPerLevel(cs.CombatRatings,"ExpertisePerQuarterPercentReduction","weapon skill")
    output += GenGORatingPerLevel(cs.CombatRatings,"HasteRatingPerHastePercent","haste melee")
    output += GenGORatingPerLevel(cs.CombatRatings,"CritRatingPerCritChance","crit melee")
    output += GenGORatingPerLevel(cs.CombatRatings,"MeleeHitRatingPerHitChance","hit melee")
    output += GenGORatingPerLevel(cs.CombatRatings,"SpellHitRatingPerHitChance","hit spell")
    output += GenGORatingPerLevel(cs.CombatRatings,"DefenseRatingPerDefense","defense skill")
    output += GenGORatingPerLevel(cs.CombatRatings,"DodgeRatingPerDodgeChance","dodge")
    output += GenGORatingPerLevel(cs.CombatRatings,"ParryRatingPerParryChance","parry")
    output += GenGORatingPerLevel(cs.CombatRatings,"BlockRatingPerBlockChance","block")
    output += GenGORatingPerLevel(cs.CombatRatings,"ResilienceRatingPerCritReductionChance","crit taken melee")

    output += '''\nvar CritPerAgi = map[proto.Class]map[int32]float64{
proto.Class_ClassUnknown:{'''
    for i in range(1,81):
        output += f"{i}:0.0,"
    output += '''},'''

    for c in ["Warrior", "Paladin", "Hunter", "Rogue", "Priest", "Death Knight", "Shaman", "Mage", "Warlock", "Druid"]:
        cName = c.split()
        if len(cName) > 1:
            cName[1] = cName[1].lower()
        cName = ''.join(cName)
        output += f"\nproto.Class_Class{cName}: {{"
        for i in range(1,81):
            mc = float(cs.MCrit[str(i)][Offs[c]])*100
            output += f"{i}:{mc:.4f},"
        output += '''},'''
    output += "\n}\n"

    output += '''var BaseCrit = map[proto.Class]stats.Stats{
proto.Class_ClassUnknown: {},'''
    for c in ["Warrior", "Paladin", "Hunter", "Rogue", "Priest", "Death Knight", "Shaman", "Mage", "Warlock", "Druid"]:
        cName = c.split()
        if len(cName) > 1:
            cName[1] = cName[1].lower()
        cName = ''.join(cName)
        output += f"\nproto.Class_Class{cName}: {{"
        scb = float(cs.SCritBase["1"][Offs[c]])*100
        mcb = float(cs.MCritBase["1"][Offs[c]])*100
        output += f"\n stats.SpellCrit: {scb:.4f},"
        output += f"\n stats.MeleeCrit: {mcb:.4f},"
        output += "\n},"
    output += "\n}\n"

    output += '''var ClassBaseStats = map[proto.Class]map[int32]stats.Stats{\nproto.Class_ClassUnknown: {'''
    currentClass = 0
    for l in ls:
        if (currentClass != l.Class):
            currentClass = l.Class
            output += f"}},\nproto.Class_Class{GetClass(l.Class)}: {{\n"
        output += f"{l.Level}: {{stats.Health: {l.BaseHP}, stats.Mana: {l.BaseMana}, stats.Strength: {l.Strength}, stats.Agility: {l.Agility}, stats.Stamina: {l.Stamina}, stats.Intellect: {l.Intellect}, stats.Spirit: {l.Spirit}}},\n"
    output += "\n},\n}\n"

    return output

def GenTSRatingPerLevel(rating: dict, variable: str, key: str):
    output = f"const {variable}: Stat = {{"
    for i in range(1,81):
        output += f"{i}:{rating[key][i-1]},"
    output += '''}\n'''
    output += f"export function GET_{variable}(level: number): number{{ return {variable}[level];}}\n"
    return output

def GenExtraStatsTSFile(cs: ClassStats):
    header = '''
// **************************************
// AUTO GENERATED BY BASE_STATS_PARSER.PY
// **************************************

interface Stat {
	[key: number]: number
}

'''

    output = header
    output += GenTSRatingPerLevel(cs.CombatRatings,"EXPERTISE_PER_QUARTER_PERCENT_REDUCTION","weapon skill")
    output += GenTSRatingPerLevel(cs.CombatRatings,"HASTE_RATING_PER_HASTE_PERCENT","haste melee")
    output += GenTSRatingPerLevel(cs.CombatRatings,"CRIT_RATING_PER_CRIT_CHANCE","crit melee")
    output += GenTSRatingPerLevel(cs.CombatRatings,"MELEE_HIT_RATING_PER_HIT_CHANCE","hit melee")
    output += GenTSRatingPerLevel(cs.CombatRatings,"SPELL_HIT_RATING_PER_HIT_CHANCE","hit spell")
    output += GenTSRatingPerLevel(cs.CombatRatings,"DEFENSE_RATING_PER_DEFENSE","defense skill")
    output += GenTSRatingPerLevel(cs.CombatRatings,"DODGE_RATING_PER_DODGE_CHANCE","dodge")
    output += GenTSRatingPerLevel(cs.CombatRatings,"PARRY_RATING_PER_PARRY_CHANCE","parry")
    output += GenTSRatingPerLevel(cs.CombatRatings,"BLOCK_RATING_PER_BLOCK_CHANCE","block")
    output += GenTSRatingPerLevel(cs.CombatRatings,"RESILIENCE_RATING_PER_CRIT_REDUCTION_CHANCE","crit taken melee")
    return output



if __name__ == "__main__":
    db = mysql.connector.connect(host="localhost", user="root", password="root", database="acore_world")

    cursor = db.cursor()
    cursor.execute("SELECT * FROM player_class_stats")
    results = cursor.fetchall()
    stats = []
    for x in results:
        level = ClassLevelStats()
        level.Class = x[0]
        level.Level = x[1]
        level.BaseHP = x[2]
        level.BaseMana = x[3]
        level.Strength = x[4]
        level.Agility = x[5]
        level.Stamina = x[6]
        level.Intellect = x[7]
        level.Spirit = x[7]
        stats.append(level)

    args = ClassStats()
    args.MCrit = GenIndexedDb(BASE_DIR + DIR_PATH + MELEE_CRIT)
    args.SCrit = GenIndexedDb(BASE_DIR + DIR_PATH + SPELL_CRIT)
    args.MCritBase = GenIndexedDb(BASE_DIR + DIR_PATH + MELEE_CRIT_BASE)
    args.SCritBase = GenIndexedDb(BASE_DIR + DIR_PATH + SPELL_CRIT_BASE)
    args.CombatRatings = GenRowIndexedDb(BASE_DIR + DIR_PATH + COMBAT_RATINGS)

    output = GenExtraStatsGoFile(args, stats)
    fname = BASE_DIR + GO_OUTPUT_PATH
    print(f"Writing stats to: {fname}")
    f = open(fname, "w")
    f.write(output)
    f.close()

    output = GenExtraStatsTSFile(args)
    fname = BASE_DIR + TS_OUTPUT_PATH
    print(f"Writing stats to: {fname}")
    f = open(fname, "w")
    f.write(output)
    f.close()
