#!/usr/bin/python

import mysql.connector
from typing import List
import csv

# Generates go/ts files for assorted values read from the acore db

def GenIntIndexedDb(file : str):
    db = {}
    with open(file) as tsv:
        first = True
        for line in csv.reader(tsv, delimiter="\t"):
            if first:
                first = False
                continue
            db[int(line[0])] = line[1:]
    return db

BASE_DIR = ""

DIR_PATH = "assets/db_inputs/spells/"
SPELL = "Spell.csv"

GO_OUTPUT_PATH = "sim/core/"
SPELLDBC = GenIntIndexedDb(DIR_PATH + SPELL)

ElixirExcludes = "32767,32766,34537,8827"
ElixirAdditions = "9088"

Off = {
    "Effect": 68,
    "EffectDie": 71,
    "EffectScaling": 74,
    "EffectBasePoints": 77,
    "EffectAura": 92,
    "EffectMiscValueA": 107,
}

Aura = {
    "damage": 13,
    "crit": 71,
    "resistance": 22,
    "stat" : 29,
    "regen": 85,
    "rating": 189,
    "health": 34,
    "attackpower": 99,
    "attackpowervs": 102,
    "penetration": 123,
    "hp5": 161,
}

SchoolMask = {
    "Physical":1,
    "Holy":2,
    "Fire":4,
    "Nature":8,
    "Frost":16,
    "Shadow":32,
    "Arcane":64,
    "Magic":126,
}

Resistance = {
    1: "Armor",
    2: "HolyResistance",
    4: "FireResistance",
    8: "NatureResistance",
    16: "FrostResistance",
    32: "ShadowResistance",
    64: "ArcaneResistance",
}

Stat = {
    0: "Strength",
    1: "Agility",
    2: "Stamina",
    3: "Intellect",
    4: "Spirit",
}

Rating = {
  1: "Defense",
  2: "Dodge",
  3: "Parry",
  4: "Block",
  5: "MeleeHit",
  7: "SpellHit",
  8: "MeleeCrit",
  10: "SpellCrit",
  14: "Resilience",
  17: "MeleeHaste",
  19: "SpellHaste",
  23: "Expertise",
  24: "ArmorPenetration",
}

class Mixology:
    entry: int
    mod: float

class Elixir:
    entry: int
    name: str
    spell: int
    level: int
    flag: int


def CleanName(name: str):
    remove = "()'-:"
    for c in remove:
        name = name.replace(c,"")
    return ''.join(name.split())

def GenMixology(mixology: List[Mixology]):
    output = '''
package core

// **************************************
// AUTO GENERATED BY MISC_PARSER.PY
// **************************************

import (
	"github.com/WoWLegacySims/wotlk/sim/core/stats"
)

var mixology = map[int32]float64{
'''
    for mix in mixology:
        output += f"{mix.entry}: {round(1+(mix.mod)/100,4)},\n"
    output += "}"
    return output

def WriteDef(flag: int):
    if flag == 1: return "enum BattleElixir {\nBattleElixirUnknown = 0;\n"
    if flag == 2: return "}\n\nenum GuardianElixir {\nGuardianElixirUnknown = 0;\n"
    if flag == 3: return "}\n\nenum Flask {\nFlaskUnknown = 0;\n"

def GenProto(elixirs: List[Elixir]):
    output = """
// **************************************
// AUTO GENERATED BY MISC_PARSER.PY
// **************************************
syntax = "proto3";
package proto;

option go_package = "./proto";

"""
    current = 0
    for el in elixirs:
        if el.flag != current:
            output += WriteDef(el.flag)
            current = el.flag

        output += f"{CleanName(el.name)} = {el.entry};\n"

    output += "}"
    return output

def GenElixirs(elixirs: List[Elixir]):
    output = "\nvar Elixirs = map[int32]stats.Stats{\n"
    for el in elixirs:
        spell = SPELLDBC[el.spell]
        output += f"{el.entry}: {{\n"
        for eff in range(0,3):
            if (spell[Off["Effect"]+eff] == 6):
                continue

            aura = int(spell[Off["EffectAura"]+eff])
            misc = int(spell[Off["EffectMiscValueA"]+eff])
            amount = int(spell[Off["EffectBasePoints"]+eff])+1

            if(aura == Aura["damage"]):
                if(misc == SchoolMask["Physical"]): output += f"stats.AttackPower: {amount},stats.RangedAttackPower: {amount},"
                elif (misc & SchoolMask["Magic"]): output += f"stats.SpellPower: {amount},"

            if(aura == Aura["stat"]):
                if(misc == -1):
                   for i in range(0,5):
                        output += f"stats.{Stat[i]}: {amount},"
                else:
                   output += f"stats.{Stat[misc]}: {amount},"

            if(aura == Aura["resistance"]):
                for i in [1,4,8,16,32,64]:
                    if(i & misc):
                        output += f"stats.{Resistance[i]}: {amount},"

            if(aura == Aura["penetration"]): output += f"stats.SpellPenetration: {-amount},"

            if(aura == Aura["regen"]):
                if(misc == 0): output += f"stats.MP5: {amount},"

            if(aura == Aura["hp5"]): output += f"/*stats.HP5: {amount},*/"

            if(aura == Aura["health"]):
                if(misc == 0): output += f"stats.Health: {amount},"

            if(aura == Aura["rating"]):
                for i, s in Rating.items():
                    if(misc & (1 << i)):
                        output += f"stats.{s}: {amount},"

            if(aura == Aura["attackpower"] or aura == Aura["attackpowervs"]):
                output += f"stats.AttackPower: {amount}, stats.RangedAttackPower: {amount},"
        output += "},\n"
    output += "}"
    return output

if __name__ == "__main__":
    db = mysql.connector.connect(host="localhost", user="root", password="root", database="acore_world")

    cursor = db.cursor()
    cursor.execute("SELECT * FROM spell_mixology")
    results = cursor.fetchall()
    mixology = []
    for x in results:
        mix = Mixology()
        mix.entry = x[0]
        mix.mod = x[1]
        mixology.append(mix)

    cursor.execute(f"""SELECT entry ,name, spellid_1, RequiredLevel, special_flag
FROM item_template
JOIN spell_group ON spellid_1 = spell_group.spell_id
WHERE ((name LIKE "%flask %" OR name LIKE "%elixir%") AND spellid_1 > 0 AND NOT name like "%recipe%" AND NOT entry IN({ElixirExcludes}) AND special_flag <= 3) OR entry IN({ElixirAdditions})
ORDER BY special_flag ASC""")
    results = cursor.fetchall()
    elixirs = []
    for x in results:
        elixir = Elixir()
        elixir.entry = x[0]
        elixir.name = x[1]
        elixir.spell = x[2]
        elixir.level = x[3]
        elixir.flag = x[4]
        elixirs.append(elixir)

    output = GenMixology(mixology)
    output += GenElixirs(elixirs)
    fname = BASE_DIR + GO_OUTPUT_PATH + "alchemy_gen.go"
    print(f"Writing stats to: {fname}")
    f = open(fname, "w")
    f.write(output)
    f.close()

    output = GenProto(elixirs)
    fname = BASE_DIR + "proto/alchemy_gen.proto"
    print(f"Writing stats to: {fname}")
    f = open(fname, "w")
    f.write(output)
    f.close()
