#!/usr/bin/python

import csv
from typing import List

DIR_PATH = "assets/db_inputs/spells/"
SPELL = "Spell.csv"
SPELL_CAST_TIMES = "SpellCastTimes.csv"
SPELL_DURATION = "SpellDuration.csv"

BASE_DIR = ""
OUT_PATH = "sim/"

Off = {
    "CastTime": 25,
    "MaxLevel": 34,
    "MinLevel": 35,
    "Duration": 37,
    "EffectDie": 71,
    "EffectScaling": 74,
    "EffectBasePoints": 77,
    "EffectAura": 92,
    "EffectAuraPeriod": 95,
    "Period": 96,
    "Name": 133,
    "BaseCost": 201,
    "Coefficient": 226,
}
class SpellEffect:
    BasePoints: str
    Die: str
    LevelScaling: str
    Coefficient: str

class SpellInfo:
    SpellID: int
    MinLevel: str
    MaxLevel: str
    Duration: str
    Period: str
    CastTime: str
    BaseCost: str
    Effects: List[SpellEffect]


def GenIndexedDb(file : str):
    db = {}
    with open(file) as tsv:
        first = True
        for line in csv.reader(tsv, delimiter="\t"):
            if first:
                first = False
                continue
            db[line[0]] = line[1:]
    return db

def GenIntIndexedDb(file : str):
    db = {}
    with open(file) as tsv:
        first = True
        for line in csv.reader(tsv, delimiter="\t"):
            if first:
                first = False
                continue
            db[int(line[0])] = line[1:]
    return db

SPELLDBC = GenIntIndexedDb(DIR_PATH + SPELL)
CASTTIMEDBC = GenIntIndexedDb(DIR_PATH + SPELL_CAST_TIMES)
DURATIONDBC = GenIntIndexedDb(DIR_PATH + SPELL_DURATION)

def WriteFile(cls: str, output: str):
    fname = BASE_DIR + OUT_PATH + cls + "/spells_gen.go"
    print(f"Writing stats to: {fname}")
    f = open(fname, "w")
    f.write(output)
    f.close()

def GenHeader(cls: str):
    return f"""
package {cls}
// **************************************
// AUTO GENERATED BY SPELLS_PARSER.PY
// **************************************

import (
	"time"
    "github.com/WoWLegacySims/wotlk/sim/core"
)
"""

SPELLS = {
    "deathknight": {
        "Blood Boil": [48721,49939,49940,49941],
        "Blood Strike": [45902,49926,49927,49928,49929,49930],
        "Death and Decay": [43265,49936,49937,49938],
        "Death Coil": [47541,49892,49893,49894,49895],
        "Death Strike": [49998,49999,45463,49923,49924],
        "Frost Strike": [49143,51416,51417,51418,51419,55268],
        "Heart Strike": [55050,55258,55259,55260,55261,55262],
        "Horn of Winter": [57330,57623],
        "Howling Blast": [49184,51409,51410,51411],
        "Icy Touch": [45477,49896,49903,49904,49909],
        "Obliterate": [49020,51423,51424,51425],
        "Plague Strike": [45462,49917,49918,49919,49920,49921],
        "Scourge Strike": [55090,55265,55270,55271]
	},
    "druid": {
        "Claw": [1082,3029,5201,9849,9850,27000,48569,48570],
        "Demoralizing Roar": [99,1735,9490,9747,9898,26998,48559,48560],
        "Ferocious Bite": [22568,22827,22828,22829,31018,24248,48576,48577],
        "Healing Touch": [5185,5186,5187,5188,5189,6778,8903,9758,9888,9889,25297,26978,26979,48377,48378],
        "Hurricane": [16914,17401,17402,27012,48467],
        "Insect Swarm": [5570,24974,24975,24976,24977,27013,48468],
        "Lacerate": [33745,48567,48568],
        "Lifebloom": [33763,48450,48451],
        "Mangle (Bear)": [33878,33986,33987,48563,48564],
        "Mangle (Cat)": [33876,33982,33983,48565,48566],
        "Mark of the Wild": [1126,5232,6756,5234,8907,9884,9885,26990,48469],
        "Maul": [6807,6808,6809,8972,9745,9880,9881,26996,48479,48480],
        "Moonfire": [8921,8924,8925,8926,8927,8928,8929,9833,9834,9835,26987,26988,48462,48463],
        "Pounce": [9005,9823,9827,27006,49803],
        "Rake": [1822,1823,1824,9904,27003,48573,48574],
        "Ravage": [6785,6787,9866,9867,27005,48578,48579],
        "Regrowth": [8936,8938,8939,8940,8941,9750,9856,9857,9858,26980,48442,48443],
        "Rejuvenation": [774,1058,1430,2090,2091,3627,8910,9839,9840,9841,25299,26981,26982,48440,48441],
        "Rip": [1079,9492,9493,9752,9894,9896,27008,49799,49800],
        "Shred": [5221,6800,8992,9829,9830,27001,27002,48571,48572],
        "Starfire": [2912,8949,8950,8951,9875,9876,25298,26986,48464,48465],
        "Swipe (Bear)": [779,780,769,9754,9908,26997,48561,48562],
        "Thorns": [467,782,1075,8914,9756,9910,26992],
        "Tiger's Fury": [5217,6793,9845,9846,50212,50213],
        "Tranquility": [740,8918,9862,9863,26983,48446,48447],
        "Wrath": [5176,5177,5178,5179,5180,6780,8905,9912,26984,26985,48459,48461],
	},
    "hunter": {
        "Aimed Shot": [19434,20900,20901,20902,20903,20904,27065,49049,49050],
        "Arcane Shot": [3044,14281,14282,14283,14284,14285,14286,14287,27019,49044,49045],
        "Aspect of the Dragonhawk": [61846,61847],
        "Aspect of the Hawk": [13165,14318,14319,14320,14321,14322,25296,27044],
        "Aspect of the Wild": [20043,20190,27045,49071],
        "Black Arrow": [3674,63668,63669,63670,63671,63672],
        "Explosive Shot": [53301,60051,60052,60053],
        "Explosive Trap": [13813,14316,14317,27025,49066,49067],
        "Explosive Trap Effect": [13812,14314,14315,27026,49064,49065],
        "Hunter's Mark": [1130,14323,14324,14325,53338],
        "Kill Shot": [53351,61005,61006],
        "Mongoose Bite": [1495,14269,14270,14271,36916,53339],
        "Multi-Shot": [2643,14288,14289,14290,25294,27021,49047,49048],
        "Raptor Strike": [2973,14260,14261,14262,14263,14264,14265,14266,27014,48995,48996],
        "Serpent Sting": [1978,13549,13550,13551,13552,13553,13554,13555,25295,27016,49000,49001],
        "Steady Shot": [56641,34120,49051,49052],
        "Volley": [1510,14294,14295,27022,58431,58434],
        #pet
        "Bite": [17253,17255,17256,17257,17258,17259,17260,17261,27050,52473,52474],
        "Claw": [16827,16828,16829,16830,16831,16832,3010,3009,27049,52471,52472],
        "Smack": [49966,49967,49968,49969,49970,49971,49972,49973,49974,52475,52476],
        "Acid Spit": [55749,55750,55751,55752,55753,55754],
        "Demoralizing Screech": [24423,24577,24578,24579,27051,55487],
        "Fire Breath": [34889,35323,55482,55483,55484,55485],
        "Froststorm Breath": [54644,55488,55489,55490,55491,55492],
        "Furious Howl": [24604,64491,64492,64493,64494,64495],
        "Gore": [35290,35291,35292,35293,35294,35295],
        "Lava Breath": [58604,58607,58608,58609,58610,58611],
        "Lightning Breath": [24844,25008,25009,25010,25011,25012],
        "Monstrous Bite": [54680,55495,55496,55497,55498,55499],
        "Nether Shock": [50479,53584,53586,53587,53588,53589],
        "Pin": [50245,53544,53545,53546,53547,53548],
        "Poison Spit": [35387,35389,35392,55555,55556,55557],
        "Rake": [59881,59882,59883,59884,59885,59886],
        "Ravage": [50518,53558,53559,53560,53561,53562],
        "Savage Rend": [50498,53578,53579,53580,53581,53582],
        "Scorpid Poison": [24640,24583,24586,24587,27060,55728],
        "Snatch": [50541,53537,53538,53540,53542,53543],
        "Sonic Blast": [50519,53564,53565,53566,53567,53568],
        "Spirit Strike": [61193,61194,61195,61196,61197,61198],
        "Spore Cloud": [50274,53593,53594,53596,53597,53598],
        "Stampede": [57386,57389,57390,57391,57392,57393],
        "Sting": [56626,56627,56628,56629,56630,56631],
        "Swipe": [50256,53526,53528,53529,53532,53533],
        "Tendon Rip": [50271,53571,53572,53573,53574,53575],
        "Venom Web Spray": [54706,55505,55506,55507,55508,55509]
	},
    "mage": {
        "Arcane Barrage": [44425,44780,44781],
        "Arcane Blast": [30451,42894,42896,42897],
        "Arcane Explosion": [1449,8437,8438,8439,10201,10202,27080,27082,42920,42921],
        "Arcane Intellect": [1459,1460,1461,10156,10157,27126,42995],
        "Arcane Missiles": [5143,5144,5145,8416,8417,10211,10212,25345,27075,38699,38704,42843,42846],
        "Blast Wave": [11113,13018,13019,13020,13021,27133,33933,42944,42945],
        "Blizzard": [10,6141,8427,10185,10186,10187,27085,42939,42940,],
        "Cone of Cold": [120,8492,10159,10160,10161,27087,42930,42931],
        "Dragon's Breath": [31661,33041,33042,33043,42949,42950],
        "Fire Blast": [2136,2137,2138,8412,8413,10197,10199,27078,27079,42872,42873],
        "Fireball": [133, 143, 145, 3140, 8400, 8401, 8402, 10148, 10149, 10150, 10151, 25306, 27070, 38692, 42832, 42833],
        "Flamestrike": [2120,2121,8422,8423,10215,10216,27086,42925,42926],
        "Frost Nova": [122,865,6131,10230,27088,42917],
        "Frostbolt": [116,205,837,7322,8406,8407,8408,10179,10180,10181,25304,27071,27072,38697,42841,42842],
        "Frostfire Bolt": [44614,47610],
        "Ice Lance": [30455,42913,42914],
        "Living Bomb": [44457,55359,55360],
        "Living Bomb Explosion": [44461,55361,55362],
        "Pyroblast": [11366,12505,12522,12523,12524,12525,12526,18809,27132,33938,42890,42891],
        "Scorch": [2948,8444,8445,8446,10205,10206,10207,27073,27074,42858,42859],
    },
    "paladin": {
        "Avenger's Shield": [31935,32699,32700,48826,48827],
        "Blessing of Might": [19740,19834,19835,19836,19837,19838,25291,27140,48931,48932],
        "Blessing of Wisdom": [19742,19850,19852,19853,19854,25290,27142,48935,48936],
        "Consecration": [26573,20116,20922,20923,20924,27173,48818,48819],
        "Devotion Aura": [465,10290,643,10291,1032,10292,10293,27149,48941,48942],
        "Exorcism": [879,5614,5615,10312,10313,10314,27138,48800,48801],
        "Fire Resistance Aura": [19891,19899,19900,27153,48947],
        "Flash of Light": [19750,19939,19940,19941,19942,19943,27137,48784,48785],
        "Frost Resistance Aura": [19888,19897,19898,27152,48945],
        "Hammer of Wrath": [24275,24274,24239,27180,48805,48806],
        "Holy Light": [635,639,647,1026,1042,3472,10328,10329,25292,27135,27136,48781,48782],
        "Holy Shield": [20925,20927,20928,27179,48951,48952],
        "Holy Shock": [20473,20929,20930,27174,33072,48824,48825],
        "Holy Shock Damage": [25912,25911,25902,27176,33073,48822,48823],
        "Holy Shock Heal": [25914,25913,25903,27175,33074,48820,48821],
        "Holy Wrath": [2812,10318,27139,48816,48817],
        "Retribution Aura": [7294,10298,10299,10300,10301,27150,54043],
        "Shadow Resistance Aura": [19876,19895,19896,27151,48943],
        "Shield of Righteousness": [53600,61411]
	},
    "priest": {
        "Binding Heal": [32546,48119,48120],
        "Circle of Healing": [34861,34863,34864,34865,34866,48088,48089],
        "Desperate Prayer": [19236,19238,19240,19241,19242,19243,25437,48172,48173],
        "Devouring Plague": [2944,19276,19277,19278,19279,19280,25467,48299,48300],
        "Divine Spirit": [14752,14818,14819,27841,25312,48073],
        "Flash Heal": [2061,9472,9473,9474,10915,10916,10917,25233,25235,48070,48071],
        "Greater Heal": [2060,10963,10964,10965,25314,25210,25213,48062,48063],
        "Heal": [2054,2055,6063,6064],
        "Holy Fire": [14914,15262,15263,15264,15265,15266,15267,15261,25384,48134,48135],
        "Holy Nova": [15237,15430,15431,27799,27800,27801,25331,48077,48078],
        "Inner Fire": [588,7128,602,1006,10951,10952,25431,48040,48168],
        "Lesser Heal": [2050,2052,2053],
        "Mind Blast": [8092,8102,8103,8104,8105,8106,10945,10946,10947,25372,25375,48126,48127],
        "Mind Flay": [15407,17311,17312,17313,17314,18807,25387,48155,48156],
        "Mind Sear": [48045,53023],
        "Penance": [47540,53005,53006,53007],
        "Penance Damage": [47666,52998,52999,53000],
        "Penance Heal": [52983,52984,52985],
        "Power Word: Fortitude": [1243,1244,1245,2791,10937,10938,25389,48161],
        "Power Word: Shield": [17,592,600,3747,6065,6066,10898,10899,10900,10901,25217,25218,48065,48066],
        "Prayer of Healing": [596,996,10960,10961,25316,25308,48072],
        "Prayer of Mending": [33076,48112,48113],
        "Renew": [139,6074,6075,6076,6077,6078,10927,10928,10929,25315,25221,25222,48067,48068],
        "Shadow Protection": [976,10957,10958,25433,48169],
        "Shadow Word: Death": [32379,32996,48157,48158],
        "Shadow Word: Pain": [589,594,970,992,2767,10892,10893,10894,25367,25368,48124,48125],
        "Smite": [585,591,598,984,1004,6060,10933,10934,25363,25364,48122,48123],
        "Vampiric Touch": [34914,34916,34917,48159,48160]
	},
    "rogue": {
        "Ambush": [8676,8724,8725,11267,11268,11269,27441,48689,48690,48691],
        "Backstab": [53,2589,2590,2591,8721,11279,11280,11281,25300,26863,48656,48657],
        "Deadly Throw": [26679,48673,48674],
        "Envenom": [32645,32684,57992,57993],
        "Eviscerate": [2098,6760,6761,6762,8623,8624,11299,11300,31016,26865,48667,48668],
        "Garrote": [703,8631,8632,8633,11289,11290,26839,26884,48675,48676],
        "Hemorrhage": [16511,17347,17348,26864,48660],
        "Mutilate": [1329,34411,34412,34413,48663,48666],
        "Rupture": [1943,8639,8640,11273,11274,11275,26867,48671,48672],
        "Sinister Strike": [1752,1757,1758,1759,1760,8621,11293,11294,26861,26862,48637,48638],
        "Slice and Dice": [5171,6774],
	},
    "shaman": {
        "Chain Heal": [1064,10622,10623,25422,25423,55458,55459],
        "Chain Lightning": [421,930,2860,10605,25439,25442,49270,49271],
        "Earth Shield": [974,32593,32594,49283,49284],
        "Earth Shock": [8042,8044,8045,8046,10412,10413,10414,25454,49230,49231],
        "Earthliving Weapon": [51730,51988,51991,51992,51993,51994],
        "Earthliving Weapon (Passive)": [51940,51989,52004,52005,52007,52008],
        "Earthliving": [51945,51990,51997,51998,51999,52000],
        "Fire Nova": [1535,8498,8499,11314,11315,25546,25547,61649,61657],
        "Fire Nova Damage": [8349,8502,8503,11306,11307,25535,25537,61650,61654],
        "Fire Resistance Totem": [8184,10537,10538,25563,58737,58739],
        "Fire Resistance": [8185,10534,10535,25562,58738,58740],
        "Flame Shock": [8050,8052,8053,10447,10448,29228,25457,49232,49233],
        "Flametongue Totem": [8227,8249,10526,16387,25557,58649,58652,58656],
        "Flametonge Totem Effect": [52109,52110,52111,52112,52113,58651,58655,58654],
        "Flametongue Weapon": [8024,8027,8030,16339,16341,16342,25489,58785,58789,58790],
        "Flametongue Weapon (Passive)": [10400,15567,15568,15569,16311,16312,16313,58784,58791,58792],
        "Frost Resistance Totem": [8181,10478,10479,25560,58741,58745],
        "Frost Resistance Totem Effect": [8182,10476,10477,25559,58742,58744],
        "Frost Shock": [8056,8058,10472,10473,25464,49235,49236],
        "Frostbrand Weapon": [8033,8038,10456,16355,16356,25500,58794,58795,58796],
        "Frostbrand Attack": [8034,8037,10458,16352,16353,25501,58797,58798],
        "Healing Stream Totem": [5394,6375,6377,10462,10463,25567,58755,58756,58757],
        "Healing Stream": [5672,6372,10460,10461,25566,58763,58764,58765],
        "Healing Wave": [331,332,547,913,939,959,8005,10395,10396,25357,25391,25396,49272,49273],
        "Lesser Healing Wave": [8004,8008,8010,10466,10467,10468,25420,49275,49276],
        "Lightning Bolt": [403,529,548,915,943,6041,10391,10392,15207,15208,25448,25449,49237,49238],
        "Lightning Shield": [324,325,905,945,8134,10431,10432,25469,25472,49280,49281],
        "Lightning Shield Effect": [26364,26366,26367,26369,26370,26363,26371,26372,49278,48279],
        "Magma Totem": [8190,10585,10586,10587,25552,58731,58734],
        "Magma Totem Effect": [8187,10579,10580,10581,25550,58732,58735],
        "Mana Spring Totem": [5675,10495,10496,10497,25570,58771,58773,58774],
        "Mana Spring": [5677,10491,10493,10494,25569,58775,58776,58777],
        "Nature Resistance Totem": [10595,10600,10601,25574,58746,58749],
        "Nature Resistance": [10596,10598,10599,25573,58748,58750],
        "Rockbiter Weapon": [8017,8018,8019,10399],
        "Searing Totem": [3599,6363,6364,6365,10437,10438,25533,58699,58703,58704],
        "Attack": [3606,6350,6351,6352,10435,10436,25530,58700,58701,58702],
        "Stoneskin Totem": [8071,8154,8155,10406,10407,10408,25508,25509,58751,58753],
        "Stoneskin": [8072,8156,8157,10403,10404,10405,25506,25507,58752,58754],
        "Strength of Earth Totem": [8075,8160,8161,10442,25361,25528,57622,58643],
        "Strength of Earth": [8076,8162,8163,10441,25362,25527,57621,58646],
        "Thunderstorm": [51490,59156,59158,59159],
        "Totem of Wrath": [30706,57720,57721,57722],
        "Totem of Wrath Effect": [57658,57660,57662,57663],
        "Water Shield": [52127,52129,52131,52134,52136,52138,24398,33736,57960],
        "Windfury Weapon": [8232,8235,10486,16362,25505,58801,58803,58804],
	},
    "warlock": {
        "Chaos Bolt": [50796,59170,59171,59172],
        "Corruption": [172,6222,6223,7648,11671,11672,25311,27216,47812,47813],
        "Curse of Agony": [980,1014,6217,11711,11712,11713,27218,47863,47864],
        "Curse of Doom": [603,30910,47867],
        "Curse of the Elements": [1490,11721,11722,27228,47865],
        "Curse of Tongues": [1714, 11719],
        "Curse of Weakness": [702,1108,6205,7646,11707,11708,27224,30909,50511],
        "Dark Pact": [18220,18937,18938,27265,59092],
        "Death Coil": [6789,17925,17926,27223,47859,47860],
        "Demon Armor": [706,1086,11733,11734,11735,27260,47793,47889],
        "Demon Skin": [687,696],
        "Drain Life": [689,699,709,7651,11699,11700,27219,27220,47857],
        "Fel Armor": [28176,28189,47892,47893],
        "Haunt": [48181,59161,59163,59164],
        "Hellfire": [1949,11683,11684,27213,47823],
        "Immolate": [348,707,1094,2941,11665,11667,11668,25309,27215,47810,47811],
        "Incinerate": [29722,32231,47837,47838],
        "Life Tap": [1454,1455,1456,11687,11688,11689,27222,57946],
        "Rain of Fire": [5740,6219,11677,11678,27212,47819,47820],
        "Searing Pain": [5676,17919,17920,17921,17922,17923,27210,30459,47814,47815],
        "Seed of Corruption": [27243,47835,47836],
        "Seed of Corruption Explosion": [27285,47833,47834],
        "Shadow Bolt": [686,695,705,1088,1106,7641,11659,11660,11661,25307,27209,47808,47809],
        "Shadowburn": [17877,18867,18868,18869,18870,18871,27263,30546,47826,47827],
        "Shadowflame": [47897,61290],
        "Shadowfury": [30283,30413,30414,47846,47847],
        "Soul Fire": [6353,17924,27211,30545,47824,47825],
        "Unstable Affliction": [30108,30404,30405,47841,47843],
        "Create Firestone": [6366,17951,17952,17953,27250,60219,60220],
        "Create Spellstone": [2362,17727,17728,28172,47886,47888],
        "Drain Soul": [1120,8288,8289,11675,27217,47855],
        #Pet
        "Cleave": [30213,30219,30223,47994],
        "Lash of Pain": [7814,7815,7816,11778,11779,11780,27274,47991,47992],
        "Shadow Bite": [54049,54050,54051,54052,54053],
        "Firebolt": [3110,7799,7800,7801,7802,11762,11763,27267,47964]
	},
    "warrior": {
        "Battle Shout": [6673,5242,6192,11549,11550,11551,25289,2048,47436],
        "Cleave": [845,7369,11608,11609,20569,25231,47519,47520],
        "Commanding Shout": [469,47439,47440],
        "Demoralizing Shout": [1160,6190,11554,11555,11556,25202,25203,47437],
        "Devastate": [20243,30016,30022,47497,47498],
        "Execute": [5308,20658,20660,20661,20662,25234,25236,47470,47471],
        "Heroic Strike": [78,284,285,1608,11564,11565,11566,11567,25286,29707,30324,47449,47450],
        "Mortal Strike": [12294,21551,21552,21553,25248,30330,47485,47486],
        "Rend": [772,6546,6547,6548,11572,11573,11574,25208,46845,47465],
        "Revenge": [6572,6574,7379,11600,11601,25288,25269,30357,57823],
        "Shield Slam": [23922,23923,23924,23925,25258,30356,47487,47488],
        "Slam": [1464,8820,11604,11605,25241,25242,47474,47475],
        "Thunder Clap": [6343,8198,8204,8205,11580,11581,25264,47501,47502]
	}
}

def ApplySpellinfoCorrections(spellInfo: SpellInfo):
    match spellInfo.SpellID:
        #Firestones
        case 6366:
            spellInfo.Effects[0].BasePoints = 7
        case 17951:
            spellInfo.Effects[0].BasePoints = 14
        case 17952:
            spellInfo.Effects[0].BasePoints = 21
        case 17953:
            spellInfo.Effects[0].BasePoints = 28
        case 27250:
            spellInfo.Effects[0].BasePoints = 35
        case 60219:
            spellInfo.Effects[0].BasePoints = 42
        case 60220:
            spellInfo.Effects[0].BasePoints = 49
        #Spellstones
        case 2362:
            spellInfo.Effects[0].BasePoints = 10
        case 17727:
            spellInfo.Effects[0].BasePoints = 20
        case 17728:
            spellInfo.Effects[0].BasePoints = 30
        case 28172:
            spellInfo.Effects[0].BasePoints = 40
        case 47886:
            spellInfo.Effects[0].BasePoints = 50
        case 47888:
            spellInfo.Effects[0].BasePoints = 60


def GetCastTime(dbc: List[str]):
    index = int(dbc[Off["CastTime"]])
    if (index):
        return CASTTIMEDBC[index][0]
    return 0

def GetDuration(dbc: List[str]):
    index = int(dbc[Off["Duration"]])
    if (index):
        return int(DURATIONDBC[index][0])
    return 0

def GetDBC(id: int):
    try:
        return SPELLDBC[id]
    except:
        print(f"{id} was not found")

def CleanName(name: str):
    remove = "()'-:"
    for c in remove:
        name = name.replace(c,"")
    return name

def GenSpellInfo(name: str, ids: List[int]):
    output = f"var {''.join(CleanName(name).split())}Infos = []*core.SpellInfo{{\n"
    level = 0
    for id in ids:
        output += "{"
        dbc = GetDBC(id)
        if (dbc == None): continue
        if(dbc[Off["Name"]] != name): print(f"Error: ID:{id} {name} does not match {dbc[Off["Name"]]}")
        spellInfo = SpellInfo()
        spellInfo.Effects = []
        spellInfo.SpellID = id
        spellInfo.CastTime = GetCastTime(dbc)
        spellInfo.Duration = GetDuration(dbc)
        spellInfo.Period = dbc[Off["Period"]]
        spellInfo.MinLevel = dbc[Off["MinLevel"]]
        spellInfo.MaxLevel = dbc[Off["MaxLevel"]]
        spellInfo.BaseCost = dbc[Off["BaseCost"]]
        for i in range(0,3):
            effect = SpellEffect()
            effect.BasePoints = dbc[Off["EffectBasePoints"] + i]
            effect.Die = dbc[Off["EffectDie"] + i]
            effect.LevelScaling = dbc[Off["EffectScaling"] + i]
            effect.Coefficient = dbc[Off["Coefficient"] + i]
            spellInfo.Effects.append(effect)

        ApplySpellinfoCorrections(spellInfo)
        output += f"SpellID:{spellInfo.SpellID},MinLevel:{spellInfo.MinLevel},MaxLevel:{spellInfo.MaxLevel},Duration:{spellInfo.Duration},Period:{spellInfo.Period},CastTime: {spellInfo.CastTime} * time.Millisecond,BaseCost: {spellInfo.BaseCost},Effects: [3]core.SpellEffect{{"
        for effect in spellInfo.Effects:
            output += f"{{BasePoints: {effect.BasePoints},Die: {effect.Die},LevelScaling: {effect.LevelScaling},Coefficient: {effect.Coefficient},}},"

        output += "},},\n"
    output += "}\n"
    return output


def GenSpells(cls: str):
    output = GenHeader(cls)
    for spell in SPELLS[cls]:
        output += GenSpellInfo(spell, SPELLS[cls][spell])

    WriteFile(cls, output)



if __name__ == "__main__":

    for cls in SPELLS:
        GenSpells(cls)

